export interface CountryData {
  name: string;
  code: string;
  flag: string;
  states: StateData[];
}

export interface StateData {
  name: string;
  code?: string;
  stations: string[];
}

export interface LocationSearchResult {
  station: string;
  state: string;
  country: string;
  flag: string;
  formatted: string;
}

export const COUNTRIES_DATA: CountryData[] = [
  // 1. INDIA (Comprehensive 28 States + 8 Union Territories + In-Depth Local/Suburban/Metro Stations)
  {
    name: "India",
    code: "IN",
    flag: "🇮🇳",
    states: [
      {
        name: "Maharashtra",
        stations: [
          // Mumbai Suburban - Western Line
          "Churchgate, Mumbai",
          "Marine Lines, Mumbai",
          "Charni Road, Mumbai",
          "Grant Road, Mumbai",
          "Mumbai Central (BCT), Mumbai",
          "Mahalaxmi, Mumbai",
          "Lower Parel, Mumbai",
          "Prabhadevi (Elphinstone Road), Mumbai",
          "Dadar Western, Mumbai",
          "Matunga Road, Mumbai",
          "Mahim Junction, Mumbai",
          "Bandra, Mumbai",
          "Bandra Kurla Complex (BKC), Mumbai",
          "Khar Road, Mumbai",
          "Santacruz, Mumbai",
          "Vile Parle, Mumbai",
          "Andheri, Mumbai",
          "Jogeshwari, Mumbai",
          "Ram Mandir, Mumbai",
          "Goregaon, Mumbai",
          "Malad, Mumbai",
          "Kandivali, Mumbai",
          "Borivali, Mumbai",
          "Dahisar, Mumbai",
          "Mira Road, Thane",
          "Bhayandar, Thane",
          "Naigaon, Palghar",
          "Vasai Road, Palghar",
          "Nallasopara, Palghar",
          "Virar, Palghar",
          "Vaitarna, Palghar",
          "Saphale, Palghar",
          "Kelve Road, Palghar",
          "Palghar Station, Palghar",
          "Boisar, Palghar",
          "Vangaon, Palghar",
          "Dahanu Road, Palghar",

          // Mumbai Suburban - Central Line
          "CSMT (Chhatrapati Shivaji Maharaj Terminus), Mumbai",
          "Masjid Bunder, Mumbai",
          "Sandhurst Road, Mumbai",
          "Byculla, Mumbai",
          "Chinchpokli, Mumbai",
          "Currey Road, Mumbai",
          "Parel, Mumbai",
          "Dadar Central, Mumbai",
          "Matunga Central, Mumbai",
          "Sion, Mumbai",
          "Kurla Central, Mumbai",
          "Vidyavihar, Mumbai",
          "Ghatkopar, Mumbai",
          "Vikhroli, Mumbai",
          "Kanjurmarg, Mumbai",
          "Bhandup, Mumbai",
          "Nahur, Mumbai",
          "Mulund, Mumbai",
          "Thane Station, Thane",
          "Kalva, Thane",
          "Mumbra, Thane",
          "Diva Junction, Thane",
          "Kopar, Thane",
          "Dombivli, Thane",
          "Thakurli, Thane",
          "Kalyan Junction, Thane",
          "Vithalwadi, Thane",
          "Ulhasnagar, Thane",
          "Ambernath, Thane",
          "Badlapur, Thane",
          "Vangani, Thane",
          "Neral Junction, Raigad",
          "Bhivpuri Road, Raigad",
          "Karjat Junction, Raigad",
          "Palasdari, Raigad",
          "Kelavli, Raigad",
          "Dolavali, Raigad",
          "Lowjee, Raigad",
          "Khopoli, Raigad",
          "Shahad, Thane",
          "Ambivli, Thane",
          "Titwala, Thane",
          "Khadavli, Thane",
          "Vasind, Thane",
          "Asangaon, Thane",
          "Atgaon, Thane",
          "Kasara, Thane",

          // Mumbai Suburban - Harbour & Trans-Harbour Line
          "Dockyard Road, Mumbai",
          "Reay Road, Mumbai",
          "Cotton Green, Mumbai",
          "Sewri, Mumbai",
          "Vadala Road, Mumbai",
          "King's Circle, Mumbai",
          "GTB Nagar (Guru Tegh Bahadur Nagar), Mumbai",
          "Chunabhatti, Mumbai",
          "Tilak Nagar, Mumbai",
          "Chembur, Mumbai",
          "Govandi, Mumbai",
          "Mankhurd, Mumbai",
          "Vashi, Navi Mumbai",
          "Sanpada, Navi Mumbai",
          "Juinagar, Navi Mumbai",
          "Nerul, Navi Mumbai",
          "Seawoods-Darave, Navi Mumbai",
          "CBD Belapur, Navi Mumbai",
          "Kharghar, Navi Mumbai",
          "Mansarovar, Navi Mumbai",
          "Khandeshwar, Navi Mumbai",
          "Panvel Junction, Navi Mumbai",
          "Digha Gaon, Navi Mumbai",
          "Airoli, Navi Mumbai",
          "Rabale, Navi Mumbai",
          "Ghansoli, Navi Mumbai",
          "Kopar Khairane, Navi Mumbai",
          "Turbhe, Navi Mumbai",
          "Uran City, Navi Mumbai",
          "JNPT (Nhava Sheva), Navi Mumbai",

          // Mumbai Key Commercial Hubs & Localities
          "Nariman Point, Mumbai",
          "Colaba / Fort, Mumbai",
          "Worli, Mumbai",
          "Prabhadevi, Mumbai",
          "Lower Parel (Kamala Mills / Palladium), Mumbai",
          "Powai (Hiranandani), Mumbai",
          "Juhu, Mumbai",
          "Versova, Mumbai",
          "Lokhandwala, Mumbai",
          "Goregaon East (Nesco / Hubtown), Mumbai",
          "Andheri East (MIDC / Chakala / SEEPZ), Mumbai",
          "Andheri West, Mumbai",
          "Malad West (Mindspace), Mumbai",
          "Kandivali East / West, Mumbai",
          "Borivali West / IC Colony, Mumbai",
          "Ghodbunder Road, Thane",
          "Majiwada / Kapurbawdi, Thane",
          "Wagle Estate, Thane",

          // Pune City, Metro & Railway Stations
          "Pune Junction (PUNE), Pune",
          "Shivajinagar Station, Pune",
          "Khadki Station, Pune",
          "Dapodi, Pune",
          "Kasarwadi, Pune",
          "Pimpri, Pune",
          "Chinchwad Station, Pune",
          "Akurdi, Pune",
          "Dehu Road, Pune",
          "Begdewadi, Pune",
          "Ghorawadi, Pune",
          "Talegaon, Pune",
          "Wadgaon, Pune",
          "Kanhe, Pune",
          "Kamshet, Pune",
          "Malavli, Pune",
          "Lonavala Station, Pune",
          "Hadapsar Station, Pune",
          "Manjari Budruk, Pune",
          "Loni, Pune",
          "Uruli, Pune",
          "Hinjewadi IT Park (Phase 1, 2, 3), Pune",
          "Kharadi IT Park (EON), Pune",
          "Viman Nagar, Pune",
          "Kalyani Nagar, Pune",
          "Koregaon Park, Pune",
          "Baner, Pune",
          "Balewadi / High Street, Pune",
          "Wakad, Pune",
          "Kothrud, Pune",
          "Aundh, Pune",
          "Swargate, Pune",
          "Magarpatta City, Pune",
          "Bavdhan, Pune",
          "Pashan, Pune",
          "Senapati Bapat Road, Pune",

          // Other Maharashtra Cities & Major Stations
          "Nagpur Junction (NGP), Nagpur",
          "Ajni Station, Nagpur",
          "Nashik Road (NK), Nashik",
          "Chhatrapati Sambhajinagar (Aurangabad - AWB)",
          "Solapur Junction (SUR), Solapur",
          "Kolhapur CSMT (KOP), Kolhapur",
          "Amravati Station, Amravati",
          "Badnera Junction, Amravati",
          "Nanded (Hazur Sahib Nanded - NED)",
          "Jalgaon Junction (JL), Jalgaon",
          "Bhusawal Junction (BSL), Jalgaon",
          "Akola Junction (AK), Akola",
          "Latur Station, Latur",
          "Dhule Station, Dhule",
          "Ahmednagar Station, Ahmednagar",
          "Chandrapur Station, Chandrapur",
          "Parbhani Junction, Parbhani",
          "Jalna Station, Jalna",
          "Sangli Station, Sangli",
          "Miraj Junction, Sangli",
          "Satara Station, Satara",
          "Karad Station, Satara",
          "Ratnagiri Station, Ratnagiri",
          "Kankavli Station, Sindhudurg",
          "Sawantwadi Road, Sindhudurg",
          "Wardha Junction, Wardha",
          "Gondia Junction, Gondia",
          "Yavatmal Station, Yavatmal",
          "Dharashiv (Osmanabad)",
          "Nandurbar Station, Nandurbar",
          "Washim Station, Washim",
          "Buldhana / Malkapur, Buldhana",
          "Bhandara Road, Bhandara",
          "Gadchiroli",
          "Hingoli",
          "Alibag, Raigad",
          "Mahad, Raigad",
          "Baramati Station, Pune",
          "Manmad Junction, Nashik",
          "Igatpuri, Nashik",
          "Shirdi (Sainagar Shirdi - SNSI)",
          "Daund Junction, Pune",
        ],
      },
      {
        name: "Delhi NCR",
        stations: [
          // Delhi Major Terminals & Railway Stations
          "New Delhi Railway Station (NDLS), Central Delhi",
          "Old Delhi Railway Station (DLI), North Delhi",
          "Hazrat Nizamuddin (NZM), South Delhi",
          "Anand Vihar Terminal (ANVT), East Delhi",
          "Delhi Sarai Rohilla (DEE), North Delhi",
          "Delhi Cantt (DEC), South West Delhi",
          "Subzi Mandi Station, North Delhi",
          "Okhla Railway Station, South Delhi",
          "Tilak Bridge, New Delhi",
          "Shakurbasti Station, West Delhi",

          // Delhi Metro / Key Business Districts
          "Connaught Place (Rajiv Chowk), New Delhi",
          "Karol Bagh, Central Delhi",
          "Nehru Place, South Delhi",
          "Saket / Select Citywalk, South Delhi",
          "Hauz Khas / IIT Delhi, South Delhi",
          "Lajpat Nagar (Central Market), South Delhi",
          "Vasant Kunj, South West Delhi",
          "Dwarka (Sector 1 to 24), South West Delhi",
          "Janakpuri / District Centre, West Delhi",
          "Rajouri Garden, West Delhi",
          "Rohini (Sector 1 to 30), North West Delhi",
          "Pitampura / Netaji Subhash Place (NSP), North West Delhi",
          "Laxmi Nagar / Preet Vihar, East Delhi",
          "Mayur Vihar (Phase 1, 2, 3), East Delhi",
          "Chandni Chowk, North Delhi",
          "Kashmere Gate ISBT, North Delhi",
          "Barakhamba Road / KG Marg, Central Delhi",
          "Bhikaji Cama Place, South Delhi",
          "Jasola / Apollo, South Delhi",
          "Aerocity / IGI Airport, New Delhi",

          // NCR - Gurgaon / Gurugram
          "Cyber City / DLF Cyber Hub, Gurugram",
          "DLF Phase 1, 2, 3, 4, 5, Gurugram",
          "Golf Course Road, Gurugram",
          "Golf Course Extension Road, Gurugram",
          "Sohna Road, Gurugram",
          "Udyog Vihar (Phase 1 to 5), Gurugram",
          "MG Road / IFFCO Chowk, Gurugram",
          "Huda City Centre (Millennium City Centre), Gurugram",
          "Sector 29 / Leisure Valley, Gurugram",
          "Sector 48, 49, 56, 57, Gurugram",
          "Manesar (IMT Manesar), Gurugram",
          "Gurgaon Railway Station (GGN), Gurugram",

          // NCR - Noida & Greater Noida
          "Sector 18 (Atta Market / Mall of India), Noida",
          "Sector 62 (IT Hub / Electronic City), Noida",
          "Sector 63, 64, 65 (Industrial Area), Noida",
          "Sector 16 / 15A (Film City), Noida",
          "Sector 137 / 142 (Advant IT Park), Noida",
          "Sector 128 / 132 (Jaypee / Expressway), Noida",
          "Sector 75 / 76 / 78 (Silicon City), Noida",
          "Noida Extension (Greater Noida West)",
          "Knowledge Park 1, 2, 3 (Greater Noida)",
          "Pari Chowk, Greater Noida",
          "Alpha / Beta / Gamma Sectors, Greater Noida",
          "Noida City Centre (Sector 32), Noida",

          // NCR - Faridabad, Ghaziabad, Sonipat
          "Old Faridabad Station, Faridabad",
          "New Industrial Town (NIT), Faridabad",
          "Sector 15 / 16 / 21, Faridabad",
          "Ballabgarh, Faridabad",
          "Ghaziabad Junction (GZB), Ghaziabad",
          "Vaishali / Kaushambi, Ghaziabad",
          "Indirapuram / Shipra Mall, Ghaziabad",
          "Vasundhara / Raj Nagar Extension, Ghaziabad",
          "Sahibabad Junction, Ghaziabad",
          "Bahadurgarh, Jhajjar",
          "Sonipat Junction / Kundli",
        ],
      },
      {
        name: "Karnataka",
        stations: [
          // Bengaluru Railway & Transit Hubs
          "KSR Bengaluru City (Majestic - SBC), Bengaluru",
          "Yesvantpur Junction (YPR), Bengaluru",
          "Bangalore Cantonment (BNC), Bengaluru",
          "Bangalore East (BNCE), Bengaluru",
          "Krishnarajapuram (KJM), Bengaluru",
          "Sir M. Visvesvaraya Terminal (SMVT Baiyappanahalli), Bengaluru",
          "Banaswadi Station, Bengaluru",
          "Yelahanka Junction, Bengaluru",
          "Carmelaram Station (Sarjapur Rd), Bengaluru",
          "Whitefield Railway Station, Bengaluru",
          "Hoodi Halt Station, Bengaluru",
          "Kengeri Station, Bengaluru",
          "Channasandra, Bengaluru",
          "Lottegollahalli, Bengaluru",
          "Hebbal Station, Bengaluru",
          "Malleshwaram Station, Bengaluru",

          // Bengaluru Key Commercial & Residential Hubs
          "Electronic City (Phase 1 & 2), Bengaluru",
          "Whitefield (ITPB / EPIP Zone), Bengaluru",
          "Koramangala (Blocks 1 to 8), Bengaluru",
          "Indiranagar (100ft Rd / 12th Main), Bengaluru",
          "HSR Layout (Sectors 1 to 7), Bengaluru",
          "Bellandur (EcoWorld / EcoSpace), Bengaluru",
          "Marathahalli (ORR), Bengaluru",
          "Sarjapur Road, Bengaluru",
          "BTM Layout (Stage 1 & 2), Bengaluru",
          "Jayanagar (Blocks 1 to 9), Bengaluru",
          "JP Nagar (Phases 1 to 8), Bengaluru",
          "Bannerghatta Road, Bengaluru",
          "Hebbal (Manyata Tech Park), Bengaluru",
          "Nagavara / Hennur Road, Bengaluru",
          "Malleshwaram / Rajajinagar, Bengaluru",
          "MG Road / Brigade Road / Church Street, Bengaluru",
          "Richmond Town / Lavelle Road, Bengaluru",
          "Kalyan Nagar / HRBR Layout, Bengaluru",
          "Domlur / Embassy Golf Links (EGL), Bengaluru",
          "Basavanagudi, Bengaluru",
          "Sadashivanagar / Vasanth Nagar, Bengaluru",
          "Peenya Industrial Area, Bengaluru",
          "Electronic City Tollgate / Bommasandra, Bengaluru",

          // Karnataka Other Cities & Stations
          "Mysuru Junction (MYS), Mysuru (Mysore)",
          "Hubballi Junction (UBL - SWR HQ), Hubli",
          "Dharwad Station, Dharwad",
          "Mangaluru Central (MAQ), Mangalore",
          "Mangaluru Junction (MAJN), Mangalore",
          "Belagavi (Belgaum - BGM)",
          "Kalaburagi Junction (Gulbarga - KLBG)",
          "Davanagere Station, Davanagere",
          "Ballari Junction (Bellary - BAY)",
          "Vijayapura (Bijapur - BJP)",
          "Shivamogga Town (Shimoga - SMET)",
          "Tumakuru (Tumkur - TK)",
          "Udupi Station, Udupi",
          "Manipal, Udupi",
          "Hassan Junction, Hassan",
          "Bidar Station, Bidar",
          "Hosapete Junction (Hampi - HPT)",
          "Raichur Junction, Raichur",
          "Gadag Junction, Gadag",
          "Bagalkot Station, Bagalkot",
          "Chikkamagaluru Station, Chikkamagaluru",
          "Karwar Station, Uttara Kannada",
          "Bhatkal Station, Uttara Kannada",
          "Kolar / KGF (Robertsonpet)",
          "Chitradurga Station, Chitradurga",
          "Mandya Station, Mandya",
          "Ramanagara Station, Ramanagara",
        ],
      },
      {
        name: "Gujarat",
        stations: [
          // Ahmedabad & Gandhinagar
          "Ahmedabad Junction (Kalupur - ADI), Ahmedabad",
          "Sabarmati Junction (SBIB / SBT), Ahmedabad",
          "Maninagar Station, Ahmedabad",
          "Gandhinagar Capital (GNC), Gandhinagar",
          "SG Highway (Sarkhej-Gandhinagar), Ahmedabad",
          "Prahlad Nagar, Ahmedabad",
          "Satellite / Shyamal, Ahmedabad",
          "Vastrapur / IIM Ahmedabad, Ahmedabad",
          "Bodakdev / Sindhu Bhavan Road (SBR), Ahmedabad",
          "Navrangpura / CG Road, Ahmedabad",
          "Ashram Road, Ahmedabad",
          "GIFT City, Gandhinagar",
          "Infocity / Koba, Gandhinagar",
          "Bopal / South Bopal, Ahmedabad",
          "Thaltej / Science City, Ahmedabad",
          "Chandkheda / Motera, Ahmedabad",
          "Naroda / Odhav Industrial Area, Ahmedabad",
          "Sanand GIDC, Ahmedabad",
          "Vatva GIDC, Ahmedabad",

          // Surat
          "Surat Railway Station (ST), Surat",
          "Udhna Junction, Surat",
          "Bhestan Station, Surat",
          "Ring Road / Textile Market, Surat",
          "Varachha / Diamond Market, Surat",
          "Adajan / Pal, Surat",
          "Vesu / VIP Road, Surat",
          "Piplod / Dumas Road, Surat",
          "Katargam, Surat",
          "Sachin GIDC, Surat",
          "Hazira Industrial Area, Surat",

          // Vadodara (Baroda)
          "Vadodara Junction (BRC), Vadodara",
          "Alkapuri / RC Dutt Road, Vadodara",
          "Sayajigunj, Vadodara",
          "Makarpura GIDC, Vadodara",
          "Gotri / Vasna Road, Vadodara",
          "Manjalpur, Vadodara",
          "Karelibaug, Vadodara",
          "Chhani / GSFC, Vadodara",

          // Rajkot & Saurashtra
          "Rajkot Junction (RJT), Rajkot",
          "Bhakti Nagar Station, Rajkot",
          "Yagnik Road / Kalawad Road, Rajkot",
          "Aji GIDC / Shapar-Veraval, Rajkot",
          "Bhavnagar Terminus (BVC), Bhavnagar",
          "Jamnagar Station (JAM), Jamnagar",
          "Junagadh Junction (JND), Junagadh",
          "Porbandar Station, Porbandar",
          "Morbi Station / Ceramic Hub, Morbi",
          "Surendranagar Junction, Surendranagar",

          // Kutch & South Gujarat
          "Gandhidham Junction (GIMB), Kutch",
          "Bhuj Station (BHUJ), Kutch",
          "Kandla Port / Mundra, Kutch",
          "Anand Junction (Milk City - ANND)",
          "Nadiad Junction (ND), Kheda",
          "Bharuch Junction (BH), Bharuch",
          "Ankleshwar Junction (Industrial - AKV)",
          "Navsari Station, Navsari",
          "Valsad Station, Valsad",
          "Vapi Station (GIDC Industrial Hub), Valsad",
          "Mehsana Junction, Mehsana",
          "Palanpur Junction, Banaskantha",
          "Patan Station, Patan",
          "Godhra Junction, Panchmahal",
          "Dahod Station, Dahod",
          "Veraval (Somnath - VRL)",
        ],
      },
      {
        name: "Tamil Nadu",
        stations: [
          // Chennai Terminals & Suburban Stations
          "Puratchi Thalaivar Dr. M.G.R Chennai Central (MAS), Chennai",
          "Chennai Egmore (MS), Chennai",
          "Tambaram (TBM), Chennai",
          "Chennai Beach (MSB), Chennai",
          "Mambalam (T. Nagar), Chennai",
          "Guindy Station, Chennai",
          "Perambur Station, Chennai",
          "Avadi Station, Chennai",
          "Tiruvallur Station, Chennai",
          "Chengalpattu Junction (CGL), Chennai",
          "St. Thomas Mount, Chennai",
          "Velachery Station (MRTS), Chennai",
          "Thiruvanmiyur Station, Chennai",
          "Kotturpuram / Kasturibai Nagar, Chennai",

          // Chennai Major Business & IT Districts
          "T. Nagar (Thyagaraya Nagar), Chennai",
          "Anna Nagar (East / West), Chennai",
          "OMR (Old Mahabalipuram Rd / IT Corridor), Chennai",
          "Sholinganallur (ELCOT SEZ), Chennai",
          "Thoraipakkam / Perungudi, Chennai",
          "Navalur / Siruseri (SIPCOT), Chennai",
          "Adyar / Besant Nagar, Chennai",
          "Mylapore / Alwarpet, Chennai",
          "Nungambakkam / Khader Nawaz Khan Rd, Chennai",
          "Mount Road / Anna Salai, Chennai",
          "Porur / DLF IT Park, Chennai",
          "Ambattur Industrial Estate, Chennai",
          "Guindy / Ekkatuthangal Industrial Estate, Chennai",
          "Saidapet / Little Mount, Chennai",
          "Kilpauk / Egmore, Chennai",
          "Royapettah / Gopalapuram, Chennai",

          // Coimbatore
          "Coimbatore Main Junction (CBE), Coimbatore",
          "Coimbatore North (CBF), Coimbatore",
          "Peelamedu / TIDEL Park, Coimbatore",
          "Gandhipuram / Cross Cut Road, Coimbatore",
          "RS Puram / DB Road, Coimbatore",
          "Saravanampatti (IT Hub), Coimbatore",
          "Singanallur / Trichy Road, Coimbatore",
          "Avinashi Road, Coimbatore",

          // Other Tamil Nadu Cities & Stations
          "Madurai Junction (MDU), Madurai",
          "Tiruchirappalli Junction (Trichy - TPJ)",
          "Salem Junction (SA), Salem",
          "Tirunelveli Junction (TEN), Tirunelveli",
          "Tiruppur Station (Knitwear Hub - TUP)",
          "Erode Junction (ED), Erode",
          "Vellore Katpadi Junction (KPD), Vellore",
          "Thoothukudi (Tuticorin - TN)",
          "Dindigul Junction (DG), Dindigul",
          "Thanjavur Junction (TJ), Thanjavur",
          "Ranipet / Walajah Road",
          "Kanchipuram Station, Kanchipuram",
          "Karur Junction, Karur",
          "Nagercoil Junction (NCJ), Kanyakumari",
          "Hosur Station (Industrial Hub - HSRA), Krishnagiri",
          "Kumbakonam Station, Thanjavur",
          "Cuddalore Port Junction, Cuddalore",
          "Nagapattinam Station, Nagapattinam",
          "Rameswaram Station (RMM), Ramanathapuram",
          "Sivakasi Station (Printing Hub), Virudhunagar",
          "Pollachi Junction, Coimbatore",
          "Ooty (Udagamandalam - UAM), Nilgiris",
        ],
      },
      {
        name: "Telangana",
        stations: [
          // Hyderabad / Secunderabad Major Railway Stations
          "Secunderabad Junction (SC), Secunderabad",
          "Hyderabad Deccan (Nampally - HYB), Hyderabad",
          "Kacheguda Railway Station (KCG), Hyderabad",
          "Lingampalli Railway Station (LPI), Hyderabad",
          "Begumpet Station (BMT), Hyderabad",
          "Charlapalli Terminal, Hyderabad",
          "Malkajgiri Junction, Secunderabad",
          "Falaknuma Station, Hyderabad",
          "Hi-Tech City MMTS Station, Hyderabad",
          "Bolarum Station, Secunderabad",
          "Sanathnagar Station, Hyderabad",
          "Sitaphalmandi Station, Secunderabad",

          // Hyderabad Major IT Hubs & Business Areas
          "Hitec City (Cyber Towers / Cyber Gateway), Hyderabad",
          "Gachibowli (Financial District / WaveRock), Hyderabad",
          "Madhapur (Mindspace IT Park), Hyderabad",
          "Kondapur / Kothaguda, Hyderabad",
          "Jubilee Hills (Road No 36 / 45 / 10), Hyderabad",
          "Banjara Hills (Road No 1, 2, 12), Hyderabad",
          "Kukatpally / KPHB Colony, Hyderabad",
          "Miyapur / Chandanagar, Hyderabad",
          "Ameerpet / SR Nagar, Hyderabad",
          "Somajiguda / Panjagutta / Raj Bhavan Rd, Hyderabad",
          "Dilsukhnagar / Kothapet, Hyderabad",
          "Uppal / Pocharam (Infosys SEZ), Hyderabad",
          "LB Nagar / Vanasthalipuram, Hyderabad",
          "Abids / Koti / Mozamjahi Market, Hyderabad",
          "Charminar / Old City, Hyderabad",
          "Mehdipatnam / Tolichowki, Hyderabad",
          "Manikonda / Puppalaguda, Hyderabad",
          "Kokapet (Neopolis), Hyderabad",
          "Kompally / Medchal Road, Hyderabad",
          "Nacharam / Mallapur Industrial Area, Hyderabad",
          "Patancheru Industrial Area, Hyderabad",

          // Telangana Other Cities & Stations
          "Warangal Station (WL), Warangal",
          "Kazipet Junction (KZJ), Warangal",
          "Nizamabad Junction (NZB), Nizamabad",
          "Karimnagar Station, Karimnagar",
          "Ramagundam Station (RDM), Peddapalli",
          "Khammam Station (KMT), Khammam",
          "Mahbubnagar Station (MBNR), Mahbubnagar",
          "Nalgonda Station, Nalgonda",
          "Adilabad Station, Adilabad",
          "Mancherial Station, Mancherial",
          "Siddipet Station, Siddipet",
          "Miryalaguda Station, Nalgonda",
          "Jagtial Station, Jagtial",
          "Suryapet",
          "Kamareddy Station, Kamareddy",
          "Tandur Station, Vikarabad",
          "Kothagudem (Bhadrachalam Road - BDCR)",
        ],
      },
      {
        name: "Andhra Pradesh",
        stations: [
          // Visakhapatnam (Vizag)
          "Visakhapatnam Junction (VSKP), Visakhapatnam",
          "Duvvada Station (DVD), Visakhapatnam",
          "Gajuwaka Industrial Hub, Visakhapatnam",
          "MVP Colony / Rushikonda IT SEZ, Visakhapatnam",
          "Siripuram / Jagadamba Centre, Visakhapatnam",
          "Madhurawada / PM Palem, Visakhapatnam",
          "Simhachalam Station, Visakhapatnam",
          "Anakapalle Station, Visakhapatnam",

          // Vijayawada & Amaravati
          "Vijayawada Junction (BZA), Vijayawada",
          "Gunadala / Ramavarappadu, Vijayawada",
          "MG Road / Benz Circle, Vijayawada",
          "Governorpet / Besant Road, Vijayawada",
          "Gannavaram (Airport / HCL Tech), Vijayawada",
          "Mangalagiri (AIIMS / IT Park), Guntur",
          "Amaravati Capital Region",

          // Other Andhra Cities & Stations
          "Guntur Junction (GNT), Guntur",
          "Nellore Station (NLR), Nellore",
          "Kurnool City (KLU), Kurnool",
          "Rajahmundry Station (RJY), East Godavari",
          "Tirupati Main (TPTY), Tirupati",
          "Renigunta Junction (RU), Tirupati",
          "Kakinada Town (CCT) / Port (COA), Kakinada",
          "Kadapa Junction (HX - YSR District)",
          "Anantapur Station (ATP), Anantapur",
          "Vizianagaram Junction (VZM), Vizianagaram",
          "Eluru Station (EE), Eluru",
          "Ongole Station (OGL), Prakasam",
          "Nandyal Junction (NDL), Nandyal",
          "Machilipatnam Station (MTM), Krishna",
          "Tenali Junction (TEL), Guntur",
          "Proddatur Station, Kadapa",
          "Chittoor Station (CTO), Chittoor",
          "Srikakulam Road (CHE), Srikakulam",
          "Bhimavaram Town (BVRT), West Godavari",
          "Tadepalligudem (TDD), West Godavari",
          "Guntakal Junction (GTL), Anantapur",
          "Hindupur Station, Sri Sathya Sai",
          "Dharmavaram Junction (DMM), Sri Sathya Sai",
          "Sri City SEZ, Tirupati District",
        ],
      },
      {
        name: "West Bengal",
        stations: [
          // Kolkata Terminals & Railway Stations
          "Howrah Junction (HWH), Kolkata / Howrah",
          "Sealdah (SDAH - North, Main, South), Kolkata",
          "Shalimar Station (SHM), Howrah",
          "Kolkata Railway Station (Chitpur - KOAA), Kolkata",
          "Santragachi Junction (SRC), Howrah",
          "Dum Dum Junction, Kolkata",
          "Ballygunge Junction, Kolkata",
          "Majerhat Station, Kolkata",
          "Bidhan Nagar Road (Ultadanga), Kolkata",
          "Budge Budge, South 24 Parganas",
          "Sonarpur Junction, South 24 Parganas",
          "Barasat Junction, North 24 Parganas",
          "Barrackpore Station, North 24 Parganas",
          "Naihati Junction, North 24 Parganas",

          // Kolkata Key Business Districts & Metro Areas
          "Salt Lake (Sector 1, 2, 3), Kolkata",
          "Salt Lake Sector V (IT Hub), Kolkata",
          "New Town (Action Area 1, 2, 3), Kolkata",
          "Park Street / Camac Street, Kolkata",
          "BBD Bagh (Dalhousie Square), Kolkata",
          "Esplanade / Dharmatala, Kolkata",
          "Gariahat / Ballygunge, Kolkata",
          "Tollygunge / Mahanayak Uttam Kumar, Kolkata",
          "Garia / Kavi Subhash Metro, Kolkata",
          "Alipore / New Alipore, Kolkata",
          "Bhawanipur / Rabindra Sadan, Kolkata",
          "Chowringhee / Elgin Road, Kolkata",
          "Kankurgachi / Phoolbagan, Kolkata",
          "Rajarhat, Kolkata",
          "Behala / Joka, Kolkata",
          "Shyambazar / Hatibagan, Kolkata",

          // West Bengal Other Cities & Stations
          "Asansol Junction (ASN), Paschim Bardhaman",
          "Siliguri Junction (SGUJ) / New Jalpaiguri (NJP), Darjeeling",
          "Durgapur Station (DGR), Paschim Bardhaman",
          "Bardhaman Junction (BWN), Purba Bardhaman",
          "Malda Town (MLDT), Malda",
          "Kharagpur Junction (KGP), Paschim Medinipur",
          "Haldia Port Station, Purba Medinipur",
          "Baharampur Court (BPC), Murshidabad",
          "Habra Station, North 24 Parganas",
          "Ranaghat Junction, Nadia",
          "Shantipur / Kalyani (IT / AIIMS), Nadia",
          "Darjeeling Station (DHR Toy Train)",
          "Jalpaiguri Station, Jalpaiguri",
          "Cooch Behar Station (COB), Cooch Behar",
          "Alipurduar Junction (APDJ), Alipurduar",
          "Purulia Junction (PRR), Purulia",
          "Bankura Station (BQA), Bankura",
          "Midnapore Station (MDN), Paschim Medinipur",
          "Bolpur Shantiniketan (BHP), Birbhum",
          "Rampurhat Junction (RPH), Birbhum",
          "Krishnanagar City Junction, Nadia",
        ],
      },
      {
        name: "Uttar Pradesh",
        stations: [
          // Lucknow
          "Lucknow Charbagh (LKO / LJN), Lucknow",
          "Gomti Nagar Railway Station (GTNR), Lucknow",
          "Aishbagh Junction, Lucknow",
          "Alambagh / Transport Nagar, Lucknow",
          "Hazratganj, Lucknow",
          "Indira Nagar / Munshi Pulia, Lucknow",
          "Vibhuti Khand (IT City), Lucknow",
          "Mahanagar / Kapoorthala, Lucknow",
          "Aliganj, Lucknow",

          // Kanpur
          "Kanpur Central (CNB), Kanpur",
          "Kanpur Anwarganj (CPA), Kanpur",
          "Govindpuri Junction, Kanpur",
          "Kalyanpur / IIT Kanpur, Kanpur",
          "Rawatpur Station, Kanpur",
          "Civil Lines / Mall Road, Kanpur",
          "Panki Dham Station, Kanpur",

          // Varanasi & Prayagraj
          "Varanasi Junction (Cantonment - BSB), Varanasi",
          "Banaras Railway Station (Manduadih - BSBS), Varanasi",
          "Pt. Deen Dayal Upadhyaya Junction (Mughalsarai - DDU)",
          "Kashi Station, Varanasi",
          "Godowlia / Dashashwamedh, Varanasi",
          "Prayagraj Junction (Allahabad - PRYJ), Prayagraj",
          "Prayagraj Chheoki (PCOI), Prayagraj",
          "Prayagraj Rambag (PRRB), Prayagraj",
          "Civil Lines, Prayagraj",

          // Agra, Mathura & Western UP
          "Agra Cantt (AGC), Agra",
          "Agra Fort (AF), Agra",
          "Sanjay Place / MG Road, Agra",
          "Mathura Junction (MTJ), Mathura",
          "Vrindavan Station, Mathura",
          "Meerut City (MTC) / Cantt (MUT), Meerut",
          "Bareilly Junction (BE), Bareilly",
          "Aligarh Junction (ALJN), Aligarh",
          "Moradabad Junction (MB), Moradabad",
          "Saharanpur Junction (SRE), Saharanpur",
          "Gorakhpur Junction (GKP), Gorakhpur",
          "Virangana Lakshmibai Jhansi Junction (VGLJ), Jhansi",
          "Ayodhya Dham Junction (AY) / Ayodhya Cantt (AYC)",
          "Firozabad Station, Firozabad",
          "Muzaffarnagar Station, Muzaffarnagar",
          "Budaun Station, Budaun",
          "Shahjahanpur Station, Shahjahanpur",
          "Etawah Junction, Etawah",
          "Mirzapur Station, Mirzapur",
          "Sitapur Junction, Sitapur",
          "Hapur Junction, Hapur",
          "Bulandshahr Station, Bulandshahr",
          "Lakhimpur Station, Kheri",
          "Banda Junction, Banda",
          "Gonda Junction (GD), Gonda",
          "Basti Station, Basti",
          "Azamgarh Station, Azamgarh",
          "Jaunpur Junction, Jaunpur",
          "Ballia Station, Ballia",
          "Deoria Sadar, Deoria",
          "Raebareli Junction, Raebareli",
          "Sultanpur Junction, Sultanpur",
        ],
      },
      {
        name: "Rajasthan",
        stations: [
          // Jaipur
          "Jaipur Junction (JP), Jaipur",
          "Gandhinagar Jaipur (GADJ), Jaipur",
          "Durgapura Railway Station (DPA), Jaipur",
          "Kanakpura Station, Jaipur",
          "Malviya Nagar / Gaurav Tower, Jaipur",
          "Mansarovar / Mansarovar Metro, Jaipur",
          "Vaishali Nagar, Jaipur",
          "C-Scheme / Ashok Nagar, Jaipur",
          "MI Road / Ajmer Gate, Jaipur",
          "Sitapura Industrial Area (RIICO), Jaipur",
          "Tonk Road / Gopalpura Bypass, Jaipur",
          "Raja Park, Jaipur",
          "Vidhyadhar Nagar, Jaipur",
          "Jagatpura, Jaipur",

          // Jodhpur, Kota & Other Rajasthan Cities
          "Jodhpur Junction (JU), Jodhpur",
          "Bhagat Ki Kothi (BGKT), Jodhpur",
          "Ratanada / Shastri Nagar, Jodhpur",
          "Kota Junction (KOTA), Kota",
          "Dakaniya Talav Station, Kota",
          "Vigyan Nagar / Indraprastha Area, Kota",
          "Bikaner Junction (BKN) / Lalgarh (LGH), Bikaner",
          "Ajmer Junction (AII), Ajmer",
          "Pushkar Terminus, Ajmer",
          "Udaipur City (UDZ) / Rana Pratap Nagar, Udaipur",
          "Bhilwara Station (Textile City - BHL)",
          "Alwar Junction (AWR), Alwar",
          "Bhiwadi Industrial Area, Alwar",
          "Sikar Junction (SIKR), Sikar",
          "Sri Ganganagar Junction (SGNR)",
          "Pali Marwar Station, Pali",
          "Bharatpur Junction (BTE), Bharatpur",
          "Hanumangarh Junction (HMH)",
          "Beawar Station, Ajmer",
          "Chittorgarh Junction (COR)",
          "Kishangarh Station (Marble City)",
          "Abu Road (Mount Abu - ABR)",
          "Jaisalmer Station (JSM)",
          "Barmer Station (BME)",
          "Sawai Madhopur Junction (Ranthambore - SWM)",
          "Nagaur Station, Nagaur",
          "Dausa Station, Dausa",
          "Churu Junction, Churu",
          "Jhunjhunu Station, Jhunjhunu",
        ],
      },
      {
        name: "Kerala",
        stations: [
          // Thiruvananthapuram (Trivandrum)
          "Thiruvananthapuram Central (TVC), Trivandrum",
          "Kochuveli Railway Station (KCVL), Trivandrum",
          "Technopark (Phase 1, 2, 3, 4), Trivandrum",
          "Kazhakkoottam Station, Trivandrum",
          "Pettah Station, Trivandrum",
          "Neyyattinkara Station, Trivandrum",
          "Varkala Sivagiri (VAK), Trivandrum",
          "Kowdiar / Pattom / Vellayambalam, Trivandrum",
          "MG Road / Palayam / Statue, Trivandrum",

          // Kochi / Cochin / Ernakulam
          "Ernakulam Junction (South - ERS), Kochi",
          "Ernakulam Town (North - ERN), Kochi",
          "Aluva Railway Station (AWY), Kochi",
          "Angamaly for Kalady (AFK), Kochi",
          "Tripunithura Station, Kochi",
          "Edappally / Lulu Mall, Kochi",
          "Kakkanad (Infopark / SmartCity), Kochi",
          "Kaloor / JLN Stadium Metro, Kochi",
          "Marine Drive / MG Road, Kochi",
          "Palarivattom / Pipeline, Kochi",
          "Vyttila Mobility Hub, Kochi",
          "Fort Kochi / Mattancherry, Kochi",
          "Kalamassery (CUSAT), Kochi",

          // Other Kerala Cities & Stations
          "Kozhikode Main (Calicut - CLT), Kozhikode",
          "Ferok Station, Kozhikode",
          "Thrissur Railway Station (TCR), Thrissur",
          "Guruvayur Station (GUV), Thrissur",
          "Kollam Junction (Quilon - QLN), Kollam",
          "Palakkad Junction (Olavakkode - PGT), Palakkad",
          "Shoranur Junction (SRR), Palakkad",
          "Alappuzha Station (Alleppey - ALLP)",
          "Kayamkulam Junction (KYJ), Alappuzha",
          "Kannur Main Station (CAN), Kannur",
          "Thalassery Station (TLY), Kannur",
          "Kottayam Railway Station (KTYM), Kottayam",
          "Changanassery Station, Kottayam",
          "Tirur Station (TIR), Malappuram",
          "Kasaragod Station (KGQ), Kasaragod",
          "Kanhangad Station, Kasaragod",
          "Thiruvalla Station, Pathanamthitta",
          "Chengannur (Sabarimala Gateway - CNGR)",
          "Muvattupuzha / Perumbavoor, Ernakulam",
          "Kattappana / Munnar, Idukki",
          "Kalpetta / Sulthan Bathery, Wayanad",
        ],
      },
      {
        name: "Madhya Pradesh",
        stations: [
          // Indore
          "Indore Junction (INDB), Indore",
          "Laxmi Bai Nagar (LMNR), Indore",
          "Vijay Nagar / Scheme 54, Indore",
          "Palasia / New Palasia, Indore",
          "Bhawarkua / AB Road, Indore",
          "Rajwada / Sarafa / MG Road, Indore",
          "Super Corridor (TCS / Infosys SEZ), Indore",
          "Pithampur Industrial Area, Dhar/Indore",
          "Rau Station, Indore",
          "Sanwer Road Industrial Area, Indore",

          // Bhopal
          "Bhopal Junction (BPL), Bhopal",
          "Rani Kamlapati (Habibganj - RKMP), Bhopal",
          "Bhopal Nishatpura Station, Bhopal",
          "MP Nagar (Zones 1 & 2), Bhopal",
          "Arera Colony / Bittan Market, Bhopal",
          "New Market / TT Nagar, Bhopal",
          "Mandideep Industrial Area, Bhopal",
          "Hoshangabad Road, Bhopal",
          "Kolar Road, Bhopal",
          "Bairagarh (Sant Hirdaram Nagar), Bhopal",

          // Other MP Cities & Stations
          "Jabalpur Junction (JBP), Jabalpur",
          "Madan Mahal Station (MML), Jabalpur",
          "Gwalior Junction (GWL), Gwalior",
          "Ujjain Junction (UJN - Mahakal City)",
          "Sagar Station (SGO), Sagar",
          "Dewas Junction (DWX), Dewas",
          "Satna Junction (STA), Satna",
          "Ratlam Junction (RTM), Ratlam",
          "Rewa Station (REWA), Rewa",
          "Katni Junction (KTE) / Murwara (KMZ), Katni",
          "Singrauli Station / Waidhan, Singrauli",
          "Burhanpur Station, Burhanpur",
          "Khandwa Junction (KNW), Khandwa",
          "Bhind Station, Bhind",
          "Chhindwara Junction, Chhindwara",
          "Guna Junction (GUNA), Guna",
          "Shivpuri Station, Shivpuri",
          "Vidisha Station, Vidisha",
          "Damoh Station, Damoh",
          "Mandsaur Station, Mandsaur",
          "Neemuch Station, Neemuch",
          "Hoshangabad (Narmadapuram - NDPM)",
          "Itarsi Junction (Major Transit - ET)",
          "Nagda Junction (NAD), Ujjain",
          "Sehore Station, Sehore",
          "Betul Station, Betul",
        ],
      },
      {
        name: "Punjab",
        stations: [
          "Ludhiana Junction (LDH), Ludhiana",
          "Amritsar Junction (ASR), Amritsar",
          "Jalandhar City (JUC) / Cantt (JRC), Jalandhar",
          "Patiala Station (PTA), Patiala",
          "Bathinda Junction (BTI), Bathinda",
          "SAS Nagar Mohali (Phase 1 to 11 / Sector 67 to 82)",
          "Pathankot Junction (PTK) / Cantt (PTKC)",
          "Hoshiarpur Station, Hoshiarpur",
          "Batala Junction, Gurdaspur",
          "Moga Station, Moga",
          "Abohar Junction, Fazilka",
          "Malerkotla Station, Malerkotla",
          "Khanna Station (Grain Market), Ludhiana",
          "Phagwara Junction (PGW), Kapurthala",
          "Muktsar (Sri Muktsar Sahib)",
          "Barnala Station, Barnala",
          "Rajpura Junction, Patiala",
          "Firozpur Cantt (FZR), Firozpur",
          "Kapurthala Station, Kapurthala",
          "Fazilka Junction, Fazilka",
          "Sangrur Station, Sangrur",
          "Faridkot Station, Faridkot",
          "Mandi Gobindgarh (Steel Town), Fatehgarh Sahib",
          "Sirhind Junction, Fatehgarh Sahib",
          "Rupnagar (Ropar)",
        ],
      },
      {
        name: "Haryana",
        stations: [
          "Gurugram (Cyber City / Sohna Rd / Golf Course Rd)",
          "Faridabad (Old Faridabad / NIT / Sector 15)",
          "Panipat Junction (Textile Hub - PNP)",
          "Ambala Cantt Junction (UMB) / City, Ambala",
          "Karnal Station (KUN), Karnal",
          "Hisar Junction (HSR), Hisar",
          "Rohtak Junction (ROK), Rohtak",
          "Sonipat Junction, Sonipat",
          "Yamunanagar Jagadhri (YJUD), Yamunanagar",
          "Panchkula (Sectors 1 to 21 / MDC)",
          "Bhiwani Junction (BNW), Bhiwani",
          "Bahadurgarh Station, Jhajjar",
          "Jind Junction (JIND), Jind",
          "Sirsa Station (SSA), Sirsa",
          "Thanesar / Kurukshetra Junction (KKDE)",
          "Kaithal Station, Kaithal",
          "Palwal Station, Palwal",
          "Rewari Junction (RE), Rewari",
          "Manesar Industrial Township (IMT Manesar)",
          "Kundli Industrial Area, Sonipat",
          "Murthal, Sonipat",
          "Narnaul Station, Mahendragarh",
          "Fatehabad",
          "Charkhi Dadri Station",
          "Tohana Station, Fatehabad",
        ],
      },
      {
        name: "Bihar",
        stations: [
          "Patna Junction (PNBE), Patna",
          "Danapur Station (DNR), Patna",
          "Patliputra Junction (PPTA), Patna",
          "Rajendra Nagar Terminal (RJPB), Patna",
          "Gaya Junction (GAYA), Gaya",
          "Muzaffarpur Junction (MFP), Muzaffarpur",
          "Bhagalpur Junction (BGP), Bhagalpur",
          "Darbhanga Junction (DBG), Darbhanga",
          "Purnea Junction (PRNA), Purnea",
          "Begusarai Station (BGS) / Barauni Junction (BJU)",
          "Katihar Junction (KIR), Katihar",
          "Munger / Jamalpur Junction (JMP)",
          "Chhapra Junction (CPR), Saran",
          "Samastipur Junction (SPJ), Samastipur",
          "Arrah Junction (ARA), Bhojpur",
          "Sasaram Junction (SSM), Rohtas",
          "Dehri On Sone (DOS), Rohtas",
          "Motihari (Bapudham Motihari - BMKI)",
          "Bettiah Station, Paschim Champaran",
          "Saharsa Junction (SHC), Saharsa",
          "Hajipur Junction (ECR HQ - HJP), Vaishali",
          "Siwan Junction (SV), Siwan",
          "Buxar Station (BXR), Buxar",
          "Kishanganj Station (KNE), Kishanganj",
          "Sitamarhi Junction, Sitamarhi",
          "Madhubani Station, Madhubani",
          "Nawada Station, Nawada",
          "Jehanabad Station, Jehanabad",
          "Aurangabad (Anugraha Narayan Road)",
        ],
      },
      {
        name: "Jharkhand",
        stations: [
          "Ranchi Junction (RNC) / Hatia (HTE), Ranchi",
          "Tatanagar Junction (Jamshedpur - TATA)",
          "Bistupur / Sakchi / Kadma, Jamshedpur",
          "Dhanbad Junction (Coal Capital - DHN)",
          "Bokaro Steel City (BKSC), Bokaro",
          "Deoghar Junction / Jasidih Junction (JSME)",
          "Hazaribagh Town / Road (HZD)",
          "Giridih Station (GRD), Giridih",
          "Ramgarh Cantt / Barkakana Junction",
          "Medininagar (Daltonganj - DTO)",
          "Chakradharpur (CKP), West Singhbhum",
          "Chaibasa Station, West Singhbhum",
          "Dumka Station, Dumka",
          "Madhupur Junction (MDP), Deoghar",
          "Gomoh (Netaji SC Bose Gomoh - GMO)",
          "Koderma Junction (KQR), Koderma",
          "Sahibganj Junction (SBG), Sahibganj",
          "Pakur Station, Pakur",
          "Simdega",
          "Khunti",
          "Gumla",
          "Lohardaga Station, Lohardaga",
          "Garhwa Town Station, Garhwa",
        ],
      },
      {
        name: "Odisha",
        stations: [
          "Bhubaneswar Railway Station (BBS), Khordha",
          "Bhubaneswar New (BBSN), Khordha",
          "Master Canteen / Saheed Nagar / Patia, Bhubaneswar",
          "Infocity / Chandrasekharpur, Bhubaneswar",
          "Cuttack Junction (CTC), Cuttack",
          "Rourkela Junction (Steel City - ROU), Sundargarh",
          "Puri Railway Station (Lord Jagannath Temple - PURI)",
          "Sambalpur Junction (SBP) / Sambalpur City",
          "Brahmapur / Berhampur Station (BAM), Ganjam",
          "Balasore Station (BLS), Balasore",
          "Bhadrak Station (BHC), Bhadrak",
          "Baripada Station, Mayurbhanj",
          "Jharsuguda Junction (JSG), Jharsuguda",
          "Angul Station (ANGL), Angul",
          "Dhenkanal Station, Dhenkanal",
          "Rayagada Station (RGDA), Rayagada",
          "Jeypore Station / Koraput Junction",
          "Balangir Station, Balangir",
          "Bargarh Road (BRGA), Bargarh",
          "Kendujhar (Keonjhar - KDJR)",
          "Paradip Port Station, Jagatsinghpur",
          "Jajpur Keonjhar Road (JJKR), Jajpur",
          "Khurda Road Junction (KUR), Khordha",
          "Talcher Station (Coal City), Angul",
        ],
      },
      {
        name: "Assam & North-East",
        stations: [
          "Guwahati Railway Station (GHY), Kamrup Metro",
          "Kamakhya Junction (KYQ), Guwahati",
          "Paltan Bazaar / GS Road / Dispur, Guwahati",
          "Dibrugarh Town / Banipur (DBRG), Dibrugarh",
          "Silchar Station (SCL), Cachar",
          "Jorhat Town (JTTN), Jorhat",
          "Nagaon / Chaparmukh Junction",
          "Tinsukia Junction / New Tinsukia (NTSK)",
          "Tezpur / Dekargaon (DKGN), Sonitpur",
          "Bongaigaon / New Bongaigaon (NBQ)",
          "Karimganj Junction, Karimganj",
          "Sivasagar Town, Sivasagar",
          "Goalpara Town, Goalpara",
          "North Lakhimpur Station, Lakhimpur",
          "Barpeta Road Station, Barpeta",
          "Lumding Junction (LMG), Hojai",
          "Rangiya Junction (RNY), Kamrup",
          "Dhubri Station, Dhubri",
          "Diphu Station, Karbi Anglong",
          "Agartala Railway Station (AGTL), Tripura",
          "Dharmanagar Station, North Tripura",
          "Shillong (Police Bazar / Laitumkhrah), Meghalaya",
          "Imphal City, Manipur",
          "Aizawl (Zarkawt / Bawngkawn), Mizoram",
          "Kohima / Dimapur Railway Station (DMV), Nagaland",
          "Itanagar / Naharlagun Station (NHLN), Arunachal Pradesh",
          "Gangtok (MG Marg), Sikkim",
        ],
      },
      {
        name: "Goa",
        stations: [
          "Madgaon Junction (Margao - MAO), South Goa",
          "Vasco da Gama Station (VSG), South Goa",
          "Karmali Railway Station (KRMI), North Goa",
          "Thivim Railway Station (North Goa Beaches - THVM)",
          "Pernem Station, North Goa",
          "Canacona Station, South Goa",
          "Panaji (Panjim / Miramar / Fontainhas), North Goa",
          "Calangute / Baga / Candolim, North Goa",
          "Anjuna / Vagator / Morjim, North Goa",
          "Mapusa Market / Bus Stand, North Goa",
          "Ponda City / Curti, South Goa",
          "Dabolim / Goa International Airport, South Goa",
          "Mopa / Manohar International Airport, North Goa",
          "Colva / Benaulim / Majorda, South Goa",
          "Curchorem / Sanvordem, South Goa",
        ],
      },
      {
        name: "Uttarakhand",
        stations: [
          "Dehradun Railway Station (DDN), Dehradun",
          "Rajpur Road / Clock Tower / Patel Nagar, Dehradun",
          "Haridwar Junction (HW), Haridwar",
          "Rishikesh / Yog Nagari Rishikesh (YNRK)",
          "Roorkee Station (IIT Roorkee - RK), Haridwar",
          "Haldwani Railway Station (HDW), Nainital",
          "Kathgodam Station (KGM), Nainital",
          "Nainital (Mall Road / Tallital / Mallital)",
          "Mussoorie (Mall Road / Library Chowk), Dehradun",
          "Rudrapur City (RUPC), Udham Singh Nagar",
          "Kashipur Junction (KPV), Udham Singh Nagar",
          "Pantnagar (Airport / University)",
          "Kotdwar Station (KTW), Pauri Garhwal",
          "Ramnagar Station (Jim Corbett - RMR), Nainital",
          "Vikasnagar, Dehradun",
          "Lalkuan Junction (LKU), Nainital",
          "Pithoragarh City",
          "Almora City",
          "Ranikhet, Almora",
          "Chamoli / Gopeshwar",
          "Uttarkashi City",
        ],
      },
      {
        name: "Himachal Pradesh",
        stations: [
          "Shimla Railway Station (Kalka-Shimla Toy Train - SML)",
          "The Mall / Ridge / Sanjauli, Shimla",
          "Dharamshala / McLeod Ganj, Kangra",
          "Manali (Mall Road / Old Manali), Kullu",
          "Kullu City / Bhuntar (Airport)",
          "Solan Railway Station (SOL), Solan",
          "Mandi Town, Mandi",
          "Kangra Railway Station (KGRA), Kangra",
          "Palampur Himachal Station (PLMX), Kangra",
          "Una Himachal Station (Vande Bharat - UHL)",
          "Baddi Industrial Hub, Solan",
          "Nalagarh Industrial Area, Solan",
          "Paonta Sahib, Sirmaur",
          "Nahan, Sirmaur",
          "Hamirpur Town, Hamirpur",
          "Bilaspur Town, Bilaspur",
          "Chamba Town, Chamba",
          "Dalhousie, Chamba",
          "Kalka Railway Station (KLK - Transit)",
          "Kaza / Spiti Valley, Lahaul and Spiti",
        ],
      },
      {
        name: "Jammu and Kashmir & Ladakh",
        stations: [
          "Jammu Tawi (JAT), Jammu",
          "Srinagar Railway Station (SINA), Srinagar",
          "Lal Chowk / Rajbagh / Boulevard Road, Srinagar",
          "Shri Mata Vaishno Devi Katra (SVDK), Reasi",
          "Udhampur Railway Station (UHP), Udhampur",
          "Anantnag Railway Station (ANT), Anantnag",
          "Baramulla Railway Station (BRML), Baramulla",
          "Budgam Railway Station (BDGM), Budgam",
          "Banihal Railway Station (BAHL), Ramban",
          "Qazigund Railway Station (QG), Kulgam",
          "Sopore Railway Station (SXZM), Baramulla",
          "Pulwama / Awantipora Station",
          "Pahalgam, Anantnag",
          "Gulmarg, Baramulla",
          "Kathua Station (KTHU), Kathua",
          "Samba Station (SMBX), Samba",
          "Leh City (Main Bazaar / Changspa), Ladakh",
          "Kargil City, Ladakh",
        ],
      },
      {
        name: "Chandigarh",
        stations: [
          "Chandigarh Junction (CDG)",
          "Sector 17 (City Centre), Chandigarh",
          "Sector 35 / 22 / 8 / 9, Chandigarh",
          "IT Park (Kishangarh), Chandigarh",
          "Industrial Area Phase 1 & 2, Chandigarh",
          "Sector 43 (ISBT), Chandigarh",
          "PGI / Panjab University (Sector 12 / 14)",
          "Manimajra, Chandigarh",
        ],
      },
      {
        name: "Puducherry & UTs",
        stations: [
          "Puducherry Railway Station (PDY), Pondicherry",
          "White Town / Promenade Beach, Pondicherry",
          "Auroville, Pondicherry / Villupuram",
          "Karaikal Station, Karaikal",
          "Daman (Nani Daman / Moti Daman)",
          "Diu Station / Fort Area",
          "Silvassa (Dadra and Nagar Haveli)",
          "Port Blair (Sri Vijaya Puram), Andaman and Nicobar",
          "Kavaratti, Lakshadweep",
        ],
      },
      {
        name: "Chhattisgarh",
        stations: [
          "Raipur Junction (R), Raipur",
          "Swami Vivekananda Airport / Naya Raipur (Atal Nagar)",
          "Pandri / Telibandha / Shankar Nagar, Raipur",
          "Bilaspur Junction (SECR HQ - BSP), Bilaspur",
          "Durg Junction (DURG), Durg",
          "Bhilai Power House (BPHB) / Bhilai Steel City",
          "Korba Station (Power Hub - KRBA), Korba",
          "Rajnandgaon Station (RJN), Rajnandgaon",
          "Raigarh Station (RIG), Raigarh",
          "Jagdalpur Station (JDB), Bastar",
          "Ambikapur Station (ABKP), Surguja",
          "Champa Junction (CPH), Janjgir-Champa",
          "Dhamtari, Dhamtari",
          "Mahasamund Station, Mahasamund",
          "Kawardha (Kabirdham)",
          "Kanker City, Kanker",
        ],
      },
    ],
  },

  // 2. UNITED STATES (All 50 States + DC)
  {
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    states: [
      {
        name: "New York",
        stations: [
          "Penn Station (New York Penn), New York NY",
          "Grand Central Terminal, New York NY",
          "Manhattan (Midtown / Downtown / Wall St), New York NY",
          "Brooklyn (Downtown / Williamsburg / DUMBO), New York NY",
          "Queens (Long Island City / Flushing / Astoria), New York NY",
          "Bronx / Staten Island, New York NY",
          "Buffalo Exchange Street / Depew, Buffalo NY",
          "Albany-Rensselaer Station, Albany NY",
          "Rochester Station, Rochester NY",
          "Syracuse Regional Transportation Center, Syracuse NY",
          "White Plains Station, Westchester NY",
          "Yonkers Station, Westchester NY",
        ],
      },
      {
        name: "California",
        stations: [
          "Los Angeles Union Station (LAX), Los Angeles CA",
          "Downtown LA / Financial District, Los Angeles CA",
          "Santa Monica / Silicon Beach, Los Angeles CA",
          "Hollywood / Beverly Hills / Century City, Los Angeles CA",
          "San Francisco 4th & King (Caltrain), San Francisco CA",
          "San Francisco Financial District / SoMa, San Francisco CA",
          "San Jose Diridon Station, San Jose CA",
          "Silicon Valley (Palo Alto / Mountain View / Sunnyvale), CA",
          "San Diego Santa Fe Depot, San Diego CA",
          "Sacramento Valley Station, Sacramento CA",
          "Oakland Jack London Square, Oakland CA",
          "Irvine Station / Orange County, CA",
          "Anaheim Regional Transportation Center (ARTIC), CA",
          "Fresno Santa Fe Station, Fresno CA",
          "Long Beach / Pasadena, CA",
        ],
      },
      {
        name: "Texas",
        stations: [
          "Houston Amtrak Station / Downtown, Houston TX",
          "Houston Energy Corridor / Galleria / Medical Center, TX",
          "Dallas Union Station / Downtown / Uptown, Dallas TX",
          "Fort Worth Central Station / Stockyards, TX",
          "Austin Amtrak Station / Downtown / Domain, Austin TX",
          "San Antonio Amtrak Station / River Walk, San Antonio TX",
          "Plano / Frisco / Irving (Las Colinas), TX",
          "El Paso Union Depot, El Paso TX",
          "Arlington / The Woodlands / Sugar Land, TX",
          "Lubbock / Amarillo / Corpus Christi, TX",
        ],
      },
      {
        name: "Illinois",
        stations: [
          "Chicago Union Station, Chicago IL",
          "Ogilvie Transportation Center, Chicago IL",
          "The Loop / Magnificent Mile / River North, Chicago IL",
          "Fulton Market / West Loop, Chicago IL",
          "Naperville Station, Naperville IL",
          "Schaumburg / Evanston / Oak Park, IL",
          "Springfield Amtrak Station, Springfield IL",
          "Champaign-Urbana Station, Champaign IL",
          "Rockford / Peoria / Bloomington, IL",
        ],
      },
      {
        name: "Washington",
        stations: [
          "King Street Station, Seattle WA",
          "Downtown Seattle / South Lake Union (Amazon HQ), WA",
          "Bellevue / Redmond (Microsoft HQ), WA",
          "Tacoma Dome Station, Tacoma WA",
          "Spokane Amtrak Station, Spokane WA",
          "Vancouver Station, Vancouver WA",
          "Olympia / Everett / Kirkland, WA",
        ],
      },
      {
        name: "Massachusetts",
        stations: [
          "Boston South Station, Boston MA",
          "Boston North Station, Boston MA",
          "Back Bay Station, Boston MA",
          "Cambridge / Kendall Square (MIT/Harvard), MA",
          "Seaport District / Financial District, Boston MA",
          "Worcester Union Station, Worcester MA",
          "Springfield Union Station, Springfield MA",
        ],
      },
      {
        name: "Florida",
        stations: [
          "Miami Central (Brightline) / Downtown / Brickell, Miami FL",
          "Miami Beach / Wynwood / Coral Gables, FL",
          "Orlando International Airport (Brightline) / Downtown, FL",
          "Tampa Union Station / Downtown / Ybor City, FL",
          "Fort Lauderdale Station (Brightline), FL",
          "West Palm Beach Station (Brightline), FL",
          "Jacksonville Amtrak Station, Jacksonville FL",
          "St. Petersburg / Clearwater, FL",
          "Tallahassee / Gainesville / Boca Raton, FL",
        ],
      },
      {
        name: "New Jersey",
        stations: [
          "Newark Penn Station, Newark NJ",
          "Newark Liberty Airport Station, Newark NJ",
          "Jersey City (Exchange Place / Newport / Grove St), NJ",
          "Hoboken Terminal, Hoboken NJ",
          "Princeton Junction, Princeton NJ",
          "Trenton Transit Center, Trenton NJ",
          "Metropark Station (Iselin / Edison), NJ",
          "Secaucus Junction, Secaucus NJ",
          "Atlantic City Rail Terminal, NJ",
        ],
      },
      {
        name: "Pennsylvania",
        stations: [
          "30th Street Station (William H. Gray III), Philadelphia PA",
          "Center City / University City / Old City, Philadelphia PA",
          "Pittsburgh Union Station (Pennsylvanian), Pittsburgh PA",
          "Harrisburg Transportation Center, Harrisburg PA",
          "Lancaster Amtrak Station, Lancaster PA",
          "Allentown / Bethlehem / Reading / Scranton, PA",
        ],
      },
      {
        name: "Georgia",
        stations: [
          "Peachtree Station (Brookwood), Atlanta GA",
          "Downtown Atlanta / Midtown / Buckhead, Atlanta GA",
          "Perimeter Center / Alpharetta / Sandy Springs, GA",
          "Savannah Amtrak Station, Savannah GA",
          "Augusta / Columbus / Macon, GA",
        ],
      },
      {
        name: "Washington D.C.",
        stations: [
          "Washington Union Station, Washington DC",
          "Capitol Hill / Downtown / K Street, Washington DC",
          "Georgetown / Dupont Circle / Navy Yard, Washington DC",
          "Foggy Bottom / Penn Quarter, Washington DC",
        ],
      },
      {
        name: "North Carolina",
        stations: [
          "Charlotte Gateway Station / Uptown, Charlotte NC",
          "Raleigh Union Station / Downtown, Raleigh NC",
          "Durham Station / Research Triangle Park (RTP), NC",
          "Greensboro J. Douglas Galyon Depot, NC",
          "Winston-Salem / Cary / Wilmington / Asheville, NC",
        ],
      },
      {
        name: "Virginia",
        stations: [
          "Arlington (Crystal City / Rosslyn / Ballston), VA",
          "Alexandria Union Station (Old Town), VA",
          "Tysons Corner / Reston / McLean (Fairfax Co), VA",
          "Richmond Main Street / Staples Mill Road, Richmond VA",
          "Norfolk / Virginia Beach / Charlottesville, VA",
        ],
      },
      {
        name: "Ohio",
        stations: [
          "Columbus Downtown / Short North / Easton, Columbus OH",
          "Cleveland Lakefront Station / Downtown / University Circle, OH",
          "Cincinnati Union Terminal / Downtown / Over-the-Rhine, OH",
          "Akron / Dayton / Toledo / Canton, OH",
        ],
      },
      {
        name: "Michigan",
        stations: [
          "Detroit Amtrak Station / Downtown / New Center, Detroit MI",
          "Ann Arbor Station (University of Michigan), Ann Arbor MI",
          "Grand Rapids Vernon J. Ehlers Station, MI",
          "Lansing / East Lansing Station, MI",
          "Troy / Southfield / Dearborn, MI",
        ],
      },
      {
        name: "Colorado",
        stations: [
          "Denver Union Station, Denver CO",
          "Downtown Denver / RiNo / LoDo / Cherry Creek, CO",
          "Boulder / Longmont / Fort Collins, CO",
          "Colorado Springs / Aurora / Lakewood, CO",
        ],
      },
      {
        name: "Arizona",
        stations: [
          "Phoenix Downtown / Biltmore / Midtown, Phoenix AZ",
          "Scottsdale (Old Town / Kierland), Scottsdale AZ",
          "Tempe (ASU) / Chandler / Mesa, AZ",
          "Tucson Amtrak Station, Tucson AZ",
          "Flagstaff Amtrak Station, Flagstaff AZ",
        ],
      },
      {
        name: "Nevada",
        stations: [
          "Las Vegas Strip / Downtown / Summerlin, Las Vegas NV",
          "Henderson / North Las Vegas, NV",
          "Reno Amtrak Station / Downtown / Midtown, Reno NV",
        ],
      },
      {
        name: "Tennessee",
        stations: [
          "Nashville Downtown / Broadway / Music Row / Gulch, TN",
          "Memphis Central Station / Downtown / Beale St, TN",
          "Knoxville / Chattanooga / Franklin, TN",
        ],
      },
      {
        name: "Minnesota",
        stations: [
          "Saint Paul Union Depot, St. Paul MN",
          "Minneapolis Downtown / North Loop / Uptown, Minneapolis MN",
          "Bloomington (Mall of America) / Rochester / Duluth, MN",
        ],
      },
      {
        name: "Other US States (AK, AL, AR, CT, DE, HI, IA, ID, IN, KS, KY, LA, MD, ME, MO, MS, MT, ND, NE, NH, NM, OK, OR, RI, SC, SD, UT, VT, WI, WV, WY, PR)",
        stations: [
          "Portland Union Station / Pearl District, OR",
          "Salt Lake City Central Station / Downtown, UT",
          "St. Louis Gateway Transportation Center, MO",
          "Kansas City Union Station, MO/KS",
          "New Orleans Union Passenger Terminal, LA",
          "Baltimore Penn Station / Inner Harbor, MD",
          "Hartford Union Station / New Haven Union Station, CT",
          "Wilmington Joseph R. Biden Jr. Station, DE",
          "Providence Amtrak Station / Downtown, RI",
          "Honolulu / Waikiki / Downtown, Oahu HI",
          "Anchorage Depot / Fairbanks Depot, AK",
          "San Juan / Santurce / Condado, Puerto Rico (PR)",
          "Indianapolis Union Station, IN",
          "Louisville / Lexington, KY",
          "Milwaukee Intermodal Station, WI",
          "Birmingham Amtrak Station, AL",
          "Little Rock Union Station, AR",
          "Des Moines / Cedar Rapids, IA",
          "Boise / Meridian / Idaho Falls, ID",
          "Wichita / Topeka, KS",
          "Portland Transportation Center, ME",
          "Jackson Union Station, MS",
          "Omaha / Lincoln, NE",
          "Albuquerque Alvarado Transportation Center, NM",
          "Oklahoma City Santa Fe Depot, OK",
          "Charleston Amtrak Station / Columbia, SC",
          "Burlington / Montpelier, VT",
          "Charleston / Morgantown, WV",
          "Cheyenne / Casper / Jackson, WY",
        ],
      },
    ],
  },

  // 3. UNITED KINGDOM
  {
    name: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
    states: [
      {
        name: "Greater London & England",
        stations: [
          "London King's Cross / St Pancras International, London",
          "London Waterloo, London",
          "London Paddington, London",
          "London Euston, London",
          "London Liverpool Street, London",
          "London Bridge, London",
          "London Victoria, London",
          "Canary Wharf / Docklands, London",
          "City of London (Bank / Moorgate / Liverpool St)",
          "Westminster / Soho / Mayfair / Covent Garden, London",
          "Stratford International / Westfield, London",
          "Birmingham New Street / Snow Hill, West Midlands",
          "Manchester Piccadilly / Victoria / Oxford Road",
          "Leeds City Station, West Yorkshire",
          "Liverpool Lime Street, Merseyside",
          "Bristol Temple Meads / Parkway, Bristol",
          "Newcastle Central Station, Tyne and Wear",
          "Sheffield Station, South Yorkshire",
          "Nottingham Station, Nottinghamshire",
          "Leicester Station, Leicestershire",
          "Southampton Central, Hampshire",
          "Brighton Station, East Sussex",
          "Reading Station, Berkshire",
          "Cambridge Station / Cambridge North, Cambridgeshire",
          "Oxford Station / Oxford Parkway, Oxfordshire",
          "Milton Keynes Central, Buckinghamshire",
          "Coventry Station, West Midlands",
          "York Railway Station, North Yorkshire",
        ],
      },
      {
        name: "Scotland",
        stations: [
          "Edinburgh Waverley / Haymarket, Edinburgh",
          "Glasgow Central / Queen Street, Glasgow",
          "Aberdeen Railway Station, Aberdeen",
          "Dundee Railway Station, Dundee",
          "Inverness Station, Scottish Highlands",
          "Stirling Station, Stirling",
          "Perth Station, Perth and Kinross",
        ],
      },
      {
        name: "Wales",
        stations: [
          "Cardiff Central / Queen Street, Cardiff",
          "Swansea Railway Station, Swansea",
          "Newport Railway Station, Newport",
          "Wrexham General, Wrexham",
          "Bangor Station, Gwynedd",
        ],
      },
      {
        name: "Northern Ireland",
        stations: [
          "Belfast Grand Central / Lanyon Place / Great Victoria Street",
          "Derry / Londonderry Station",
          "Lisburn Station, County Antrim",
          "Newry Station, County Down",
        ],
      },
    ],
  },

  // 4. UNITED ARAB EMIRATES
  {
    name: "United Arab Emirates",
    code: "AE",
    flag: "🇦🇪",
    states: [
      {
        name: "Dubai",
        stations: [
          "Burj Khalifa / Downtown Dubai / Dubai Mall Metro",
          "Dubai Marina / DMCC Metro / JBR",
          "Business Bay Metro / Executive Towers",
          "Jumeirah Lakes Towers (JLT)",
          "Deira / Union Metro / Al Rigga / City Centre",
          "Bur Dubai / Burjuman Metro / Al Fahidi",
          "Al Barsha / Mall of the Emirates Metro",
          "Palm Jumeirah / Atlantis / The Pointe",
          "Dubai International Financial Centre (DIFC)",
          "Dubai Internet City / Media City Metro",
          "Dubai Silicon Oasis (DSO)",
          "Dubai Sports City / Motor City / Studio City",
          "Al Quoz Industrial Area",
          "Al Rashidiya / Centrepoint Metro",
          "Jebel Ali Free Zone (JAFZA)",
          "Dubai Hills Estate / MBR City",
          "City Walk / Jumeirah 1, 2, 3",
          "Dubai Festival City / Al Garhoud",
          "Al Nahda / Al Qusais Metro",
        ],
      },
      {
        name: "Abu Dhabi",
        stations: [
          "Corniche / Downtown Abu Dhabi / Al Danah",
          "Al Reem Island / Maryah Island (ADGM)",
          "Yas Island / Yas Mall / Yas Marina",
          "Saadiyat Island / Cultural District",
          "Khalidiya / Al Bateen / Al Mushrif",
          "Musaffah Industrial Area / ICAD",
          "Khalifa City / Masdar City",
          "Al Ain Central / Town Centre",
          "Al Ruwais / Western Region (Al Dhafra)",
        ],
      },
      {
        name: "Sharjah & Northern Emirates",
        stations: [
          "Al Majaz Waterfront / Corniche, Sharjah",
          "Al Nahda / Sahara Centre, Sharjah",
          "Al Qasimia / Rolla / Central Souq, Sharjah",
          "Sharjah Airport International Free Zone (SAIF Zone)",
          "Muwaileh Commercial / University City, Sharjah",
          "Ajman Corniche / Downtown / City Centre, Ajman",
          "Ajman Free Zone / Jurf Industrial Area, Ajman",
          "Ras Al Khaimah City / Al Hamra / Marjan Island, RAK",
          "RAK Economic Zone (RAKEZ), Ras Al Khaimah",
          "Fujairah City / Port of Fujairah / Dibba, Fujairah",
          "Umm Al Quwain City / UAQ Free Trade Zone",
        ],
      },
    ],
  },

  // 5. CANADA
  {
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    states: [
      {
        name: "Ontario",
        stations: [
          "Union Station, Downtown Toronto ON",
          "Toronto Financial District / King West / Yonge-Dundas, ON",
          "Mississauga (Square One / City Centre), ON",
          "Brampton (Downtown / Bramalea GO), ON",
          "Scarborough Town Centre / North York Centre, ON",
          "Markham / Richmond Hill / Vaughan (VMC), ON",
          "Ottawa Central Station / Parliament Hill, ON",
          "Hamilton GO Centre / West Harbour, ON",
          "Waterloo / Kitchener (Silicon Valley North), ON",
          "London VIA Rail Station, London ON",
          "Windsor Station / Oakville / Burlington, ON",
        ],
      },
      {
        name: "British Columbia",
        stations: [
          "Waterfront Station (SkyTrain / SeaBus), Vancouver BC",
          "Downtown Vancouver / Yaletown / Coal Harbour, BC",
          "Richmond-Brighouse / YVR Airport, BC",
          "Burnaby (Metrotown / Brentwood), BC",
          "Surrey Central Station / King George, BC",
          "Victoria (Downtown / Inner Harbour), Vancouver Island BC",
          "Kelowna / Kamloops / Nanaimo, BC",
        ],
      },
      {
        name: "Quebec",
        stations: [
          "Gare Centrale (Central Station), Montreal QC",
          "Downtown Montreal / Old Montreal / Plateau, QC",
          "Laval / Longueuil / West Island, QC",
          "Gare du Palais, Quebec City QC",
          "Gatineau / Sherbrooke / Trois-Rivieres, QC",
        ],
      },
      {
        name: "Alberta",
        stations: [
          "Calgary Downtown (CTrain / 7th Ave Corridor / Beltline), AB",
          "Edmonton Downtown (LRT / Churchill Station / ICE District), AB",
          "Red Deer / Lethbridge / Fort McMurray, AB",
        ],
      },
      {
        name: "Other Canadian Provinces (MB, SK, NS, NB, NL, PE, NT, YT, NU)",
        stations: [
          "Winnipeg Union Station / Downtown / The Forks, MB",
          "Saskatoon VIA Station / Regina Downtown, SK",
          "Halifax VIA Station / Downtown / Dartmouth, NS",
          "Moncton Station / Fredericton / Saint John, NB",
          "St. John's Downtown / Avalon, NL",
          "Charlottetown Downtown, PE",
          "Yellowknife, NT / Whitehorse, YT / Iqaluit, NU",
        ],
      },
    ],
  },

  // 6. AUSTRALIA
  {
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    states: [
      {
        name: "New South Wales",
        stations: [
          "Central Station, Sydney NSW",
          "Town Hall Station / CBD / Martin Place, Sydney NSW",
          "Wynyard Station / Barangaroo / Circular Quay, Sydney NSW",
          "Parramatta Station / Western Sydney CBD, NSW",
          "Chatswood / North Sydney / Macquarie Park, NSW",
          "Bondi Junction / Redfern / Strathfield, Sydney NSW",
          "Newcastle Interchange, Newcastle NSW",
          "Wollongong Station, Wollongong NSW",
        ],
      },
      {
        name: "Victoria",
        stations: [
          "Flinders Street Station, Melbourne VIC",
          "Southern Cross Station (Spencer St), Melbourne VIC",
          "Melbourne CBD / Southbank / Docklands, VIC",
          "Richmond / South Yarra / Footscray, Melbourne VIC",
          "Box Hill / Clayton / Ringwood, Melbourne VIC",
          "Geelong Railway Station, Geelong VIC",
          "Ballarat / Bendigo Station, VIC",
        ],
      },
      {
        name: "Queensland",
        stations: [
          "Brisbane Central Station / Queen Street, Brisbane QLD",
          "Roma Street Station / South Bank / Fortitude Valley, QLD",
          "Gold Coast (Surfers Paradise / Robina / Helensvale), QLD",
          "Sunshine Coast (Maroochydore / Caloundra), QLD",
          "Cairns / Townsville / Toowoomba, QLD",
        ],
      },
      {
        name: "Western Australia & Others (WA, SA, ACT, TAS, NT)",
        stations: [
          "Perth Underground / Perth Station / CBD / Elizabeth Quay, WA",
          "Fremantle / Joondalup / Mandurah, WA",
          "Adelaide Railway Station / CBD / North Terrace, SA",
          "Canberra Railway Station / Civic (City Centre), ACT",
          "Hobart Transit Centre / Launceston, TAS",
          "Darwin Transit Centre / Palmerston, NT",
        ],
      },
    ],
  },

  // 7. SINGAPORE
  {
    name: "Singapore",
    code: "SG",
    flag: "🇸🇬",
    states: [
      {
        name: "Central & CBD",
        stations: [
          "Raffles Place MRT (CBD Financial Hub)",
          "Marina Bay / Marina Bay Sands / Bayfront MRT",
          "Tanjong Pagar / Shenton Way / Anson Rd MRT",
          "Orchard / Somerset / Dhoby Ghaut MRT",
          "City Hall / Bugis / Promenade MRT",
          "Clarke Quay / Chinatown / Telok Ayer MRT",
        ],
      },
      {
        name: "East, West & North Regions",
        stations: [
          "Jurong East MRT (Jurong Gateway / Second CBD)",
          "Buona Vista / One-North (Biopolis / Fusionopolis)",
          "Changi Airport / Expo MRT / Changi Business Park",
          "Paya Lebar / Tampines / Pasir Ris MRT",
          "Woodlands MRT (Causeway Gateway)",
          "Bishan / Ang Mo Kio / Serangoon MRT",
        ],
      },
    ],
  },

  // 8. SAUDI ARABIA
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
    states: [
      {
        name: "Riyadh Province",
        stations: [
          "King Abdullah Financial District (KAFD), Riyadh",
          "Olaya / King Fahd Road / Kingdom Centre, Riyadh",
          "Riyadh Railway Station (SAR / SRO), Riyadh",
          "Al Malaz / Diplomatic Quarter (DQ), Riyadh",
          "Al Nakheel / King Saud University, Riyadh",
          "Al Kharj / Diriyah",
        ],
      },
      {
        name: "Makkah & Western Province",
        stations: [
          "Haramain High Speed Rail Station, Jeddah",
          "Al Balad / Tahlia Street / Corniche, Jeddah",
          "King Abdulaziz International Airport (KAIA), Jeddah",
          "Haramain High Speed Rail Station, Makkah",
          "Haramain High Speed Rail Station, Madinah",
          "King Abdullah Economic City (KAEC) Station",
          "Taif City Centre / Al Hada",
        ],
      },
      {
        name: "Eastern Province",
        stations: [
          "Dammam SAR Railway Station, Dammam",
          "Al Khobar (Corniche / Al Rashid Mall / Dhahran)",
          "Jubail Industrial City, Jubail",
          "Al Ahsa (Hofuf Railway Station)",
        ],
      },
    ],
  },

  // 9. GERMANY
  {
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    states: [
      {
        name: "Berlin & Brandenburg",
        stations: [
          "Berlin Hauptbahnhof (Central Station), Berlin",
          "Berlin Alexanderplatz / Friedrichstraße / Zoo",
          "Berlin Ostbahnhof / Potsdamer Platz",
          "Potsdam Hauptbahnhof, Brandenburg",
        ],
      },
      {
        name: "Bavaria (Bayern)",
        stations: [
          "München Hauptbahnhof (Munich Central), Munich",
          "München Marienplatz / Ostbahnhof, Munich",
          "Nürnberg Hauptbahnhof, Nuremberg",
          "Augsburg / Regensburg / Würzburg Hauptbahnhof",
        ],
      },
      {
        name: "Hesse (Hessen)",
        stations: [
          "Frankfurt (Main) Hauptbahnhof (Financial Hub), Frankfurt",
          "Frankfurt Flughafen (Airport) Fernbahnhof",
          "Wiesbaden / Kassel / Darmstadt Hauptbahnhof",
        ],
      },
      {
        name: "North Rhine-Westphalia (NRW)",
        stations: [
          "Köln Hauptbahnhof (Cologne Central), Cologne",
          "Düsseldorf Hauptbahnhof, Dusseldorf",
          "Dortmund / Essen / Duisburg / Bonn Hauptbahnhof",
        ],
      },
      {
        name: "Other German States (Baden-Württemberg, Hamburg, etc.)",
        stations: [
          "Hamburg Hauptbahnhof / Altona, Hamburg",
          "Stuttgart Hauptbahnhof, Stuttgart",
          "Karlsruhe / Mannheim / Heidelberg Hauptbahnhof",
          "Hannover Hauptbahnhof, Lower Saxony",
          "Leipzig / Dresden Hauptbahnhof, Saxony",
          "Bremen Hauptbahnhof, Bremen",
        ],
      },
    ],
  },

  // 10. FRANCE
  {
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    states: [
      {
        name: "Île-de-France (Paris Region)",
        stations: [
          "Gare du Nord (Eurostar / Thalys), Paris",
          "Gare de Lyon (TGV Sud-Est), Paris",
          "Gare Montparnasse (TGV Atlantique), Paris",
          "Gare Saint-Lazare / Gare de l'Est, Paris",
          "La Défense (Business District / RER A), Paris",
          "Châtelet - Les Halles, Paris",
        ],
      },
      {
        name: "Auvergne-Rhône-Alpes & Provence",
        stations: [
          "Lyon Part-Dieu / Lyon Perrache, Lyon",
          "Marseille Saint-Charles, Marseille",
          "Nice-Ville / Cannes / Antibes, French Riviera",
          "Toulouse-Matabiau / Bordeaux Saint-Jean",
          "Lille-Flandres / Lille-Europe, Hauts-de-France",
          "Strasbourg-Ville, Grand Est",
          "Nantes / Rennes / Montpellier Saint-Roch",
        ],
      },
    ],
  },

  // 11. JAPAN
  {
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    states: [
      {
        name: "Tokyo & Kanto",
        stations: [
          "Tokyo Station (Shinkansen Hub), Chiyoda Tokyo",
          "Shinjuku Station (World's Busiest), Shinjuku Tokyo",
          "Shibuya Station / Scramble Crossing, Shibuya Tokyo",
          "Ikebukuro / Shinagawa / Akihabara / Ueno, Tokyo",
          "Yokohama Station / Minato Mirai, Kanagawa",
          "Shin-Yokohama (Shinkansen), Kanagawa",
          "Chiba / Saitama-Shintoshin / Omiya Station",
        ],
      },
      {
        name: "Kansai & Others (Osaka, Kyoto, Nagoya, Fukuoka)",
        stations: [
          "Osaka Station / Umeda / Namba, Osaka",
          "Shin-Osaka Station (Shinkansen), Osaka",
          "Kyoto Station (Shinkansen), Kyoto",
          "Nagoya Station (JR Central / Shinkansen), Aichi",
          "Hakata Station (Fukuoka / Shinkansen), Fukuoka",
          "Sapporo Station / Susukino, Hokkaido",
          "Hiroshima / Sendai / Kobe Station",
        ],
      },
    ],
  },

  // 12. OTHER TOP GLOBAL COUNTRIES (Comprehensive global coverage)
  {
    name: "Qatar",
    code: "QA",
    flag: "🇶🇦",
    states: [
      {
        name: "Doha & Baladiyat",
        stations: [
          "Doha Corniche / West Bay (Financial District)",
          "Souq Waqif / Msheireb Downtown Doha Metro",
          "The Pearl-Qatar / Porto Arabia / Qanat Quartier",
          "Lusail City (Lusail Marina / Stadium / Boulevard)",
          "Hamad International Airport / Al Matar Al Qadeem",
          "Al Sadd / Al Waab / Villaggio Mall Metro",
          "Al Rayyan / Education City Metro",
          "Al Wakrah / Ras Laffan / Mesaieed",
        ],
      },
    ],
  },
  {
    name: "Kuwait",
    code: "KW",
    flag: "🇰🇼",
    states: [
      {
        name: "Kuwait Governorates",
        stations: [
          "Kuwait City (Sharq / Mirqab / Qibla / Dasman)",
          "Salmiya / Salem Al Mubarak Street",
          "Hawalli / Jabriya / Maidan Hawalli",
          "Farwaniya / Kuwait International Airport",
          "Shuwaikh Industrial Area / Port",
          "Ahmadi / Fahaheel / Mahboula / Mangaf",
          "Jahra / Subiya (Silk City)",
        ],
      },
    ],
  },
  {
    name: "Oman",
    code: "OM",
    flag: "🇴🇲",
    states: [
      {
        name: "Muscat & Governorates",
        stations: [
          "Muscat (Ruwi / CBD / Muttrah Corniche)",
          "Al Khuwair / Qurum / Shatti Al Qurum, Muscat",
          "Seeb / Al Mouj / Muscat International Airport",
          "Bousher / Ghala Industrial Area, Muscat",
          "Salalah / Dhofar",
          "Sohar Port & Freezone / Al Batinah",
          "Nizwa / Sur / Duqm Special Economic Zone",
        ],
      },
    ],
  },
  {
    name: "Bahrain",
    code: "BH",
    flag: "🇧🇭",
    states: [
      {
        name: "Manama & Governorates",
        stations: [
          "Manama (Diplomatic Area / Bahrain Financial Harbour)",
          "Seef District / City Centre / Reef Island",
          "Juffair / Adliya / Mahooz, Capital Governorate",
          "Amwaj Islands / Diyar Al Muharraq, Muharraq",
          "Riffa / Isa Town / Sitra Industrial Area",
        ],
      },
    ],
  },
  {
    name: "Malaysia",
    code: "MY",
    flag: "🇲🇾",
    states: [
      {
        name: "Kuala Lumpur & Selangor",
        stations: [
          "KL Sentral (Transit Hub), Kuala Lumpur",
          "KLCC / Petronas Towers / Bukit Bintang, Kuala Lumpur",
          "Bangsar / Mid Valley Megamall, Kuala Lumpur",
          "Petaling Jaya (Damansara / Bandar Utama), Selangor",
          "Subang Jaya / Sunway / Shah Alam, Selangor",
          "Cyberjaya (Global Tech Hub) / Putrajaya",
          "George Town / Bayan Lepas, Penang",
          "Johor Bahru (JB Sentral / Iskandar Puteri), Johor",
        ],
      },
    ],
  },
  {
    name: "Indonesia",
    code: "ID",
    flag: "🇮🇩",
    states: [
      {
        name: "Jakarta & Java",
        stations: [
          "Gambir Railway Station / Monas, Central Jakarta",
          "Sudirman / SCBD / Thamrin MRT Corridor, Jakarta",
          "Pasar Senen Station, Jakarta",
          "Halim High-Speed Rail Station (Whoosh), Jakarta",
          "Tegalluar Whoosh Station / Bandung Station, West Java",
          "Surabaya Gubeng / Pasar Turi, East Java",
          "Yogyakarta Station (Tugu) / Lempuyangan",
          "Denpasar / Kuta / Seminyak / Ubud, Bali",
        ],
      },
    ],
  },
  {
    name: "Thailand",
    code: "TH",
    flag: "🇹🇭",
    states: [
      {
        name: "Bangkok & Provinces",
        stations: [
          "Krung Thep Aphiwat Central Terminal (Bang Sue), Bangkok",
          "Siam BTS Interchange / Sukhumvit / Asok BTS, Bangkok",
          "Silom / Sathorn (Financial District), Bangkok",
          "Phaya Thai (Airport Rail Link), Bangkok",
          "Pattaya Central / Chonburi",
          "Chiang Mai Railway Station, Chiang Mai",
          "Phuket Town / Patong Beach, Phuket",
        ],
      },
    ],
  },
  {
    name: "Philippines",
    code: "PH",
    flag: "🇵🇭",
    states: [
      {
        name: "Metro Manila & Regions",
        stations: [
          "Makati CBD (Ayala Avenue / BGC Link), Metro Manila",
          "Bonifacio Global City (BGC), Taguig Metro Manila",
          "Ortigas Center (Pasig / Mandaluyong), Metro Manila",
          "Tutuban Central Station (PNR), Manila",
          "Quezon City (North EDSA / Cubao / Eastwood)",
          "Cebu City / Mandaue / IT Park, Cebu",
          "Davao City / Clark Freeport Zone, Pampanga",
        ],
      },
    ],
  },
  {
    name: "Pakistan",
    code: "PK",
    flag: "🇵🇰",
    states: [
      {
        name: "Sindh, Punjab & Islamabad",
        stations: [
          "Karachi Cantt / Karachi City Station, Karachi",
          "Clifton / DHA / I.I. Chundrigar Rd, Karachi",
          "Lahore Junction Railway Station, Lahore",
          "Gulberg / DHA / Mall Road, Lahore",
          "Islamabad Railway Station / Blue Area, Islamabad",
          "Rawalpindi Railway Station, Rawalpindi",
          "Faisalabad / Multan / Peshawar / Quetta Cantt",
        ],
      },
    ],
  },
  {
    name: "Bangladesh",
    code: "BD",
    flag: "🇧🇩",
    states: [
      {
        name: "Dhaka & Divisions",
        stations: [
          "Kamalapur Railway Station, Dhaka",
          "Dhaka Metro Rail (Uttara / Mirpur / Motijheel), Dhaka",
          "Gulshan / Banani / Dhanmondi, Dhaka",
          "Chittagong Railway Station, Chattogram",
          "Agrabad Commercial Area / Port, Chattogram",
          "Sylhet / Rajshahi / Khulna Railway Station",
        ],
      },
    ],
  },
  {
    name: "Nepal",
    code: "NP",
    flag: "🇳🇵",
    states: [
      {
        name: "Bagmati & Provinces",
        stations: [
          "Kathmandu (Thamel / Durbar Marg / New Road)",
          "Lalitpur (Patan) / Bhaktapur",
          "Pokhara (Lakeside / Airport), Gandaki",
          "Birgunj / Biratnagar / Janakpurdham Station",
        ],
      },
    ],
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "🇱🇰",
    states: [
      {
        name: "Western & Other Provinces",
        stations: [
          "Colombo Fort Railway Station, Colombo",
          "Maradana Railway Station, Colombo",
          "Galle Face / Kollupitiya / Bambalapitiya, Colombo",
          "Kandy Railway Station, Central Province",
          "Galle Railway Station / Matara, Southern Province",
          "Jaffna Railway Station, Northern Province",
        ],
      },
    ],
  },
  {
    name: "South Africa",
    code: "ZA",
    flag: "🇿🇦",
    states: [
      {
        name: "Gauteng & Western Cape",
        stations: [
          "Johannesburg Park Station / Sandton Gautrain, JHB",
          "Rosebank / Pretoria Gautrain Station, Gauteng",
          "Cape Town Railway Station / Foreshore / V&A Waterfront",
          "Durban Central / Umhlanga, KwaZulu-Natal",
        ],
      },
    ],
  },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
    states: [
      {
        name: "North & South Islands",
        stations: [
          "Britomart Transport Centre (Waitematā), Auckland",
          "Newmarket / Commercial Bay, Auckland",
          "Wellington Railway Station / Lambton Quay, Wellington",
          "Christchurch Railway Station, Canterbury",
          "Queenstown / Dunedin / Hamilton",
        ],
      },
    ],
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
    states: [
      {
        name: "Swiss Cantons",
        stations: [
          "Zürich Hauptbahnhof (Zurich HB), Zurich",
          "Geneva Cornavin (Genève-Cornavin), Geneva",
          "Basel SBB / Bern Hauptbahnhof, Bern",
          "Lausanne / Lucerne (Luzern) / Lugano Station",
        ],
      },
    ],
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
    states: [
      {
        name: "North & South Holland",
        stations: [
          "Amsterdam Centraal / Amsterdam Zuid / Zuidas, Amsterdam",
          "Rotterdam Centraal / Port of Rotterdam",
          "Den Haag Centraal (The Hague) / Beatrixkwartier",
          "Utrecht Centraal (Transit Hub) / Eindhoven (High Tech)",
        ],
      },
    ],
  },
  {
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    states: [
      {
        name: "Lombardy, Lazio & Regions",
        stations: [
          "Roma Termini / Roma Tiburtina, Rome",
          "Milano Centrale / Milano Porta Garibaldi, Milan",
          "Firenze Santa Maria Novella (SMN), Florence",
          "Venezia Santa Lucia / Mestre, Venice",
          "Napoli Centrale / Torino Porta Nuova / Bologna Centrale",
        ],
      },
    ],
  },
  {
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    states: [
      {
        name: "Madrid, Catalonia & Regions",
        stations: [
          "Madrid Atocha / Madrid Chamartín, Madrid",
          "Barcelona Sants / Plaça de Catalunya, Barcelona",
          "Valencia Joaquín Sorolla / Sevilla Santa Justa",
          "Málaga María Zambrano / Bilbao-Abando",
        ],
      },
    ],
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "🇮🇪",
    states: [
      {
        name: "Leinster, Munster & Connacht",
        stations: [
          "Dublin Heuston / Dublin Connolly / Grand Canal Dock",
          "Cork Kent Station / Limerick Colbert Station",
          "Galway Ceannt Station / Waterford Station",
        ],
      },
    ],
  },
  {
    name: "Sweden",
    code: "SE",
    flag: "🇸🇪",
    states: [
      {
        name: "Stockholm, Scania & West",
        stations: [
          "Stockholm Central Station (Stockholms Centralstation)",
          "Göteborg Centralstation (Gothenburg Central)",
          "Malmö Centralstation, Scania",
          "Uppsala Centralstation / Lund Centralstation",
        ],
      },
    ],
  },
  {
    name: "Turkey",
    code: "TR",
    flag: "🇹🇷",
    states: [
      {
        name: "Marmara & Central Anatolia",
        stations: [
          "Istanbul Söğütlüçeşme / Marmaray / Kadıköy, Istanbul",
          "Levent / Maslak (Financial Hub), Istanbul",
          "Ankara YHT Garı (High Speed Terminal), Ankara",
          "Izmir Alsancak / Basmane / Antalya City",
        ],
      },
    ],
  },
  {
    name: "Egypt",
    code: "EG",
    flag: "🇪🇬",
    states: [
      {
        name: "Cairo & Alexandria",
        stations: [
          "Ramses Railway Station (Mahattat Ramsis), Cairo",
          "New Administrative Capital (NAC) / Smart Village, Cairo",
          "Misr Station (Mahattat Misr), Alexandria",
          "Giza Railway Station / 6th of October City",
        ],
      },
    ],
  },
  {
    name: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    states: [
      {
        name: "São Paulo & Rio de Janeiro",
        stations: [
          "Estação da Luz / Paulista / Faria Lima / Berrini, São Paulo",
          "Central do Brasil / Copacabana / Centro, Rio de Janeiro",
          "Brasília Rodoferroviária / Belo Horizonte Central",
          "Curitiba / Porto Alegre / Salvador",
        ],
      },
    ],
  },
  {
    name: "Mexico",
    code: "MX",
    flag: "🇲🇽",
    states: [
      {
        name: "CDMX & States",
        stations: [
          "Buenavista Suburban Station / Polanco / Reforma, Mexico City",
          "Guadalajara Centro / Zapopan, Jalisco",
          "Monterrey Centro / San Pedro Garza García, Nuevo León",
          "Cancún / Querétaro / Puebla",
        ],
      },
    ],
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    states: [
      {
        name: "Seoul & Gyeonggi",
        stations: [
          "Seoul Station (KTX / AREX), Seoul",
          "Gangnam Station / Teheran-ro, Seoul",
          "Yongsan Station / Yeouido Financial Hub, Seoul",
          "Busan Station (KTX), Busan",
          "Dongdaegu Station (Daegu) / Incheon / Suwon",
        ],
      },
    ],
  },
  {
    name: "China",
    code: "CN",
    flag: "🇨🇳",
    states: [
      {
        name: "Tier 1 Metros & Provinces",
        stations: [
          "Beijing South / Beijing West Railway Station, Beijing",
          "Shanghai Hongqiao / Shanghai Station / Lujiazui, Shanghai",
          "Shenzhen North / Futian / Nanshan Tech Hub, Shenzhen",
          "Guangzhou South / Tianhe CBD, Guangzhou",
          "Hangzhou East / Chengdu East / Wuhan Railway Station",
          "Hong Kong West Kowloon High Speed Station, Hong Kong SAR",
        ],
      },
    ],
  },
  {
    name: "Russia",
    code: "RU",
    flag: "🇷🇺",
    states: [
      {
        name: "Moscow & Saint Petersburg",
        stations: [
          "Leningradsky / Yaroslavsky / Kazansky Station, Moscow",
          "Moscow International Business Center (Moskva-City)",
          "Moskovsky Railway Station / Nevsky Prospect, Saint Petersburg",
          "Novosibirsk / Yekaterinburg / Nizhny Novgorod",
        ],
      },
    ],
  },
  {
    name: "Vietnam",
    code: "VN",
    flag: "🇻🇳",
    states: [
      {
        name: "Hanoi & Ho Chi Minh City",
        stations: [
          "Hanoi Railway Station (Ga Hà Nội) / Hoan Kiem, Hanoi",
          "Saigon Railway Station (Ga Sài Gòn) / District 1, HCMC",
          "Da Nang Railway Station, Da Nang",
          "Hai Phong / Nha Trang / Can Tho",
        ],
      },
    ],
  },
  // Additional Global Countries for complete world-wide coverage
  {
    name: "Afghanistan",
    code: "AF",
    flag: "🇦🇫",
    states: [{ name: "Kabul & Provinces", stations: ["Kabul City", "Herat", "Mazar-i-Sharif", "Kandahar"] }],
  },
  {
    name: "Albania",
    code: "AL",
    flag: "🇦🇱",
    states: [{ name: "Tirana & Counties", stations: ["Tirana Central", "Durrës Port", "Vlorë", "Shkodër"] }],
  },
  {
    name: "Algeria",
    code: "DZ",
    flag: "🇩🇿",
    states: [{ name: "Algiers & Provinces", stations: ["Agha Railway Station, Algiers", "Oran Station", "Constantine", "Annaba"] }],
  },
  {
    name: "Argentina",
    code: "AR",
    flag: "🇦🇷",
    states: [{ name: "Buenos Aires & Provinces", stations: ["Retiro Station, Buenos Aires", "Constitución Station, Buenos Aires", "Córdoba Mitre", "Rosario Norte", "Mendoza"] }],
  },
  {
    name: "Austria",
    code: "AT",
    flag: "🇦🇹",
    states: [{ name: "Vienna & States", stations: ["Wien Hauptbahnhof (Vienna Central)", "Wien Westbahnhof", "Salzburg Hauptbahnhof", "Innsbruck Hauptbahnhof", "Graz Hauptbahnhof", "Linz Hauptbahnhof"] }],
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "🇧🇪",
    states: [{ name: "Brussels & Regions", stations: ["Bruxelles-Midi (Brussels South - Eurostar)", "Bruxelles-Central", "Antwerpen-Centraal (Antwerp)", "Gent-Sint-Pieters (Ghent)", "Liège-Guillemins", "Brugge (Bruges)"] }],
  },
  {
    name: "Chile",
    code: "CL",
    flag: "🇨🇱",
    states: [{ name: "Santiago & Regions", stations: ["Estación Central, Santiago", "Providencia / Las Condes, Santiago", "Valparaíso / Viña del Mar", "Concepción", "Antofagasta"] }],
  },
  {
    name: "Colombia",
    code: "CO",
    flag: "🇨🇴",
    states: [{ name: "Bogotá & Departments", stations: ["Bogotá (Chapinero / Santa Fe / Usaquén)", "Medellín (El Poblado / Laureles / Metro)", "Cali Centro", "Barranquilla", "Cartagena (Bocagrande / Historic Center)"] }],
  },
  {
    name: "Czech Republic",
    code: "CZ",
    flag: "🇨🇿",
    states: [{ name: "Prague & Regions", stations: ["Praha hlavní nádraží (Prague Main Station)", "Praha-Holešovice", "Brno hlavní nádraží", "Ostrava hlavní nádraží", "Plzeň hlavní nádraží"] }],
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "🇩🇰",
    states: [{ name: "Copenhagen & Regions", stations: ["København H (Copenhagen Central)", "Nørreport Station, Copenhagen", "Aarhus H", "Odense Banegård", "Aalborg Station"] }],
  },
  {
    name: "Finland",
    code: "FI",
    flag: "🇫🇮",
    states: [{ name: "Helsinki & Regions", stations: ["Helsingin päärautatieasema (Helsinki Central)", "Pasila Station, Helsinki", "Tampereen rautatieasema", "Turun päärautatieasema", "Oulun rautatieasema"] }],
  },
  {
    name: "Greece",
    code: "GR",
    flag: "🇬🇷",
    states: [{ name: "Athens & Regions", stations: ["Athens Larissa Railway Station, Athens", "Syntagma / Monastiraki, Athens", "Piraeus Port & Metro", "Thessaloniki Railway Station", "Patras", "Heraklion, Crete"] }],
  },
  {
    name: "Hungary",
    code: "HU",
    flag: "🇭🇺",
    states: [{ name: "Budapest & Counties", stations: ["Budapest Keleti pályaudvar (Eastern Station)", "Budapest Nyugati pályaudvar (Western)", "Budapest Déli (Southern)", "Debrecen", "Szeged", "Győr"] }],
  },
  {
    name: "Israel",
    code: "IL",
    flag: "🇮🇱",
    states: [{ name: "Tel Aviv & Districts", stations: ["Tel Aviv HaShalom / Savidor Center / HaHagana", "Jerusalem Yitzhak Navon Station", "Haifa Merkaz HaShmona", "Beer Sheva Center", "Herzliya"] }],
  },
  {
    name: "Jordan",
    code: "JO",
    flag: "🇯🇴",
    states: [{ name: "Amman & Governorates", stations: ["Amman (Abdali / 7th Circle / Shmeisani)", "Zarqa", "Irbid", "Aqaba Port & Special Economic Zone"] }],
  },
  {
    name: "Kenya",
    code: "KE",
    flag: "🇰🇪",
    states: [{ name: "Nairobi & Counties", stations: ["Nairobi Terminus (SGR Syokimau)", "Nairobi CBD / Westlands / Upper Hill", "Mombasa Terminus (SGR Miritini)", "Kisumu", "Nakuru", "Eldoret"] }],
  },
  {
    name: "Lebanon",
    code: "LB",
    flag: "🇱🇧",
    states: [{ name: "Beirut & Governorates", stations: ["Beirut (Hamra / Downtown / Achrafieh)", "Tripoli", "Sidon (Saida)", "Byblos (Jbeil)", "Zahle"] }],
  },
  {
    name: "Luxembourg",
    code: "LU",
    flag: "🇱🇺",
    states: [{ name: "Luxembourg", stations: ["Gare de Luxembourg (Central Station)", "Kirchberg (EU Financial Hub)", "Esch-sur-Alzette", "Differdange"] }],
  },
  {
    name: "Maldives",
    code: "MV",
    flag: "🇲🇻",
    states: [{ name: "Malé & Atolls", stations: ["Malé City (Henveiru / Maafannu)", "Hulhumalé (Phase 1 & 2)", "Velana International Airport", "Addu City"] }],
  },
  {
    name: "Mauritius",
    code: "MU",
    flag: "🇲🇺",
    states: [{ name: "Port Louis & Districts", stations: ["Port Louis (Victoria Urban Terminal)", "Cybercity Ébène", "Rose Hill Central Metro", "Curepipe Central", "Grand Baie"] }],
  },
  {
    name: "Morocco",
    code: "MA",
    flag: "🇲🇦",
    states: [{ name: "Casablanca & Regions", stations: ["Casa-Port / Casa-Voyageurs (Al Boraq TGV)", "Rabat-Ville / Rabat-Agdal (Al Boraq TGV)", "Tanger-Ville (Al Boraq TGV)", "Marrakech Railway Station", "Fes-Ville", "Agadir"] }],
  },
  {
    name: "Nigeria",
    code: "NG",
    flag: "🇳🇬",
    states: [{ name: "Lagos & States", stations: ["Mobolaji Johnson Station (Ebute Metta), Lagos", "Victoria Island / Ikoyi / Lekki, Lagos", "Ikeja / Maryland / Yaba, Lagos", "Idu Railway Station / Central Area, Abuja", "Port Harcourt / Ibadan / Kano Station"] }],
  },
  {
    name: "Norway",
    code: "NO",
    flag: "🇳🇴",
    states: [{ name: "Oslo & Counties", stations: ["Oslo Sentralstasjon (Oslo S)", "Nationaltheatret Station, Oslo", "Bergen Stasjon", "Trondheim S", "Stavanger Stasjon", "Tromsø"] }],
  },
  {
    name: "Peru",
    code: "PE",
    flag: "🇵🇪",
    states: [{ name: "Lima & Regions", stations: ["Estación Central (Metropolitano), Lima", "Miraflores / San Isidro Financial Hub, Lima", "Cusco (Wanchaq / Poroy - Machu Picchu)", "Arequipa", "Trujillo"] }],
  },
  {
    name: "Poland",
    code: "PL",
    flag: "🇵🇱",
    states: [{ name: "Masovian & Voivodeships", stations: ["Warszawa Centralna (Warsaw Central)", "Warszawa Zachodnia / Wschodnia", "Kraków Główny (Krakow Main)", "Wrocław Główny", "Poznań Główny", "Gdańsk Główny", "Katowice"] }],
  },
  {
    name: "Portugal",
    code: "PT",
    flag: "🇵🇹",
    states: [{ name: "Lisbon & Porto", stations: ["Lisboa Oriente / Lisboa Santa Apolónia, Lisbon", "Baixa-Chiado / Saldanha, Lisbon", "Porto São Bento / Porto-Campanhã, Porto", "Coimbra-B", "Faro (Algarve)", "Braga / Funchal, Madeira"] }],
  },
  {
    name: "Romania",
    code: "RO",
    flag: "🇷🇴",
    states: [{ name: "Bucharest & Counties", stations: ["București Nord (Bucharest North)", "Piața Victoriei / Pipera, Bucharest", "Cluj-Napoca Gara", "Timișoara Nord", "Iași", "Brașov", "Constanța"] }],
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "🇱🇰",
    states: [{ name: "Colombo & Provinces", stations: ["Colombo Fort Railway Station", "Maradana Railway Station", "Kandy Railway Station", "Galle Railway Station", "Jaffna Railway Station"] }],
  },
  {
    name: "Ukraine",
    code: "UA",
    flag: "🇺🇦",
    states: [{ name: "Kyiv & Oblasts", stations: ["Kyiv-Pasazhyrskyi (Kyiv Central)", "Khreshchatyk / Maidan, Kyiv", "Lviv Holovnyi Railway Station", "Odesa-Holovna", "Kharkiv-Pasazhyrskyi", "Dnipro-Holovnyi"] }],
  },
];

// Popular countries for fast 1-click pills
export const POPULAR_COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "United Arab Emirates",
  "Canada",
  "Australia",
  "Singapore",
  "Saudi Arabia",
  "Germany",
  "Qatar",
];

// Search helper across all countries, states, and stations/cities
export function searchLocations(query: string, maxResults: number = 30): LocationSearchResult[] {
  if (!query || !query.trim()) return [];

  const q = query.trim().toLowerCase();
  const results: LocationSearchResult[] = [];
  const seen = new Set<string>();

  // 1. Search stations/cities within states
  for (const country of COUNTRIES_DATA) {
    for (const state of country.states) {
      for (const station of state.stations) {
        const fullStr = `${station}, ${state.name}, ${country.name}`.toLowerCase();
        if (fullStr.includes(q)) {
          const key = `${station}|${state.name}|${country.name}`;
          if (!seen.has(key)) {
            seen.add(key);
            results.push({
              station,
              state: state.name,
              country: country.name,
              flag: country.flag,
              formatted: `${station}, ${state.name}, ${country.name}`,
            });
            if (results.length >= maxResults) return results;
          }
        }
      }

      // Also match if user searches state name (returns State, Country)
      if (state.name.toLowerCase().includes(q)) {
        const key = `${state.name}|${country.name}`;
        if (!seen.has(key)) {
          seen.add(key);
          results.push({
            station: state.name,
            state: state.name,
            country: country.name,
            flag: country.flag,
            formatted: `${state.name}, ${country.name}`,
          });
          if (results.length >= maxResults) return results;
        }
      }
    }

    // Match if user searches country name
    if (country.name.toLowerCase().includes(q)) {
      const key = `${country.name}`;
      if (!seen.has(key)) {
        seen.add(key);
        results.push({
          station: country.name,
          state: "",
          country: country.name,
          flag: country.flag,
          formatted: country.name,
        });
        if (results.length >= maxResults) return results;
      }
    }
  }

  return results;
}
